### ISSUE TITLE
Cannot run nvtop with fermi GPU

### ISSUE THREAD

**Issue by TommyJerryMairo** [Syllo/nvtop#100]
I'm trying to monitor GPU usage on my ArchLinux laptop, where a dedicated Fermi GPU(GT720m) is soldered on the motherboard. As Nvidia has dropped Fermi's support on mainstream drivers, I have to use the 390 legacy driver.

```
[tjm@ArchPad ~]$ pacman -Qi nvidia-390xx-dkms
Name            : nvidia-390xx-dkms
Version         : 390.141-3
Description     : NVIDIA drivers - module sources
Architecture    : x86_64
URL             : https://www.nvidia.com/
Licenses        : custom
Groups          : None
Provides        : NVIDIA-MODULE
Depends On      : dkms  nvidia-390xx-utils=390.141  libglvnd
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 26.87 MiB
Packager        : Unknown Packager
Build Date      : Thu 15 Apr 2021 07:59:32 AM PDT
Install Date    : Thu 15 Apr 2021 09:40:18 AM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```
The driver works, as from the information provided by Xorg and glxinfo. However, I'm still encountering errors while attempting to run nvtop

```
[tjm@ArchPad ~]$ pacman -Qi nvtop
Name            : nvtop
Version         : 1.1.0-2
Description     : An htop like monitoring tool for NVIDIA GPUs
Architecture    : x86_64
URL             : https://github.com/Syllo/nvtop
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : nvidia-utils  ncurses
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 59.27 KiB
Packager        : Konstantin Gizdov <arch@kge.pw>
Build Date      : Tue 16 Feb 2021 12:58:27 AM PST
Install Date    : Tue 13 Apr 2021 04:21:29 AM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

[tjm@ArchPad ~]$ nvtop 
nvtop: symbol lookup error: nvtop: undefined symbol: nvmlDeviceGetGraphicsRunningProcesses_v2

```
Any suggestions on this circumstance?

**Comment by Syllo** [comment]
Hi,

Did you install an NVIDIA driver from outside the arch repository?

This undefined symbol is a function that has been added into recent drivers.
The only reason this happens is that there is multiple libnvidia-lm.so installed on your system.
You could check this with the command ```find / -name "libnvidia-ml*" 2>/dev/null```

**Comment by Syllo** [comment]
This problem should be fixed with the latest version in the master branch.

**Comment by Syllo** [comment]
I'll do a proper release some time soon, in a week or two to get potential breaking bugs introduced in the master branch version.
I'll contact the arch maintainer to get the version updated after that.
