### ISSUE TITLE
Option to display temp in graph

### ISSUE THREAD

**Issue by alcomposer** [Syllo/nvtop#101]
I would like to be able to add temp display to the graph.
Possibly it would be great to be able to add any metric to the graph- if possible via a <graph> FunctionN button?

**Comment by Syllo** [comment]
Hi,

Good idea indeed, but tricky to implement within the current code base.

When I have got the time, I will rewrite the graph section so that we could select the information being displayed.

**Comment by Syllo** [comment]
Hey,

If you are willing to beta test, I got a version where different metrics can be displayed in the graph in the setup_window branch.

**Comment by Syllo** [comment]
Merged into master.
