### ISSUE TITLE
installing on Ubuntu causes uninstallation of driver

### ISSUE THREAD

**Issue by Goddard** [Syllo/nvtop#112]
I think because of dependencies, or something I am unsure, but installing on Ubuntu caused my Nvidia driver to be uninstalled.  This is ubuntu 21.04.

**Comment by Syllo** [comment]
Duplicate of #51

I just updated the package for a release on Debian.

Once the Debian nvidia maintainer pushes the package to debian testing, Ubuntu should pull the update, which will fix the dependency issue.
