### ISSUE TITLE
Don't Match DviceID

### ISSUE THREAD

**Issue by KaiT0417** [Syllo/nvtop#114]
Thank you for a nice tool.

The gpu's IDs of nvidia-smi does not match the gpu's IDs of nvtop, is this a problem in my environment?

I'm not a native speaker of English, so I apologize if this is difficult to understand.

**Comment by Syllo** [comment]
Hey,

Sorry for the delayed reply.
The IDs displayed by nvtop are not necessarily the same as the NVIDIA device ID. However the devices should always show up in the same order.
For example, if the system has 3 GPUs with IDs [0,1,2], and GPU 1 is blacklisted, the GPU with NVIDIA ID 2 will be attributed the ID 1 in nvtop.

**Comment by KaiT0417** [comment]
Thank you!

I understand very well. I was able to solve it quickly.
