### ISSUE TITLE
Merge/combine output with htop

### ISSUE THREAD

**Issue by sevagh** [Syllo/nvtop#117]
Hello!

I've been interested in having a single ncurses GUI that has both the information of htop and nvtop.

In htop, there is the following issue to add nvidia GPU usage stats: https://github.com/htop-dev/htop/issues/526 

I'm wondering if as the author of nvtop you have any suggestion for a way I can somehow run htop + nvtop in a combined manner - like a "ncurses-master" process which has both nvtop + htop concatenated outputs.

**Comment by Syllo** [comment]
Hey,

I am not aware of anything that could merge two ncurses programs.
Have you considered using a terminal multiplexer like ``tmux`` or ``screen`` ?
That way you can split your terminal in half (vertically or horizontally) and run ``nvtop`` and ``htop``.
The output would be similar to this:
![tmux_example](https://user-images.githubusercontent.com/2741868/132991065-a43ec7b5-0248-481b-9063-e3c34b5b325c.png)
