### ISSUE TITLE
Impossible to initialize nvidia nvml : Driver/library version mismatch

### ISSUE THREAD

**Issue by Robanan** [Syllo/nvtop#118]
`$sudo apt install nvtop`
uninstalls a bunch of packages from nvidia 470 proprietary drivers in ubuntu 21 and then complains when I try to run it

**Comment by Syllo** [comment]
Hey,

I do not maintain the package on Ubuntu and it has been broken for some time now.
It is somehow pinned to the driver used while generating the nvtop package, that is why it downgrades your driver.

See #51
