### ISSUE TITLE
Cannot find GPUs

### ISSUE THREAD

**Issue by nasyxx** [Syllo/nvtop#122]
Hi, I successfully build the nvtop but it cannot find my GPUs.

I'm not sure which part should I provide here.

+ Build with `cmake .. && make -j`
+ run with `src/nvtop`
+ output: No GPU to monitor.
+ no conda in my machine
+ the lib is /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1

nvidia-smi works fine:

<img width="807" alt="Screen Shot 2021-09-30 at 02 05 14 PM" src="https://user-images.githubusercontent.com/5007613/135515592-d2f28309-1da0-4c99-9462-0bb00dbb0d8e.png">

<img width="523" alt="Screen Shot 2021-09-30 at 02 05 53 PM" src="https://user-images.githubusercontent.com/5007613/135515641-4962f5a0-97c8-4cdf-a83f-8e4fafd637f7.png">

**Comment by Syllo** [comment]
Hi,

This is likely a problem related to ldconfig (shared library runtime binding).
You can check with ```ldconfig -p | grep libnvidia-ml```
If the output is empty this means that you need to add the `/usr/lib/x86_64-linux-gnu/` directory to the config under `/etc/ld.so.conf` or a in a new file under `/etc/ld.so.conf.d` depending on your distribution.

**Comment by nasyxx** [comment]
> Hi,
> 
> This is likely a problem related to ldconfig (shared library runtime binding). You can check with `ldconfig -p | grep libnvidia-ml` If the output is empty this means that you need to add the `/usr/lib/x86_64-linux-gnu/` directory to the config under `/etc/ld.so.conf` or a in a new file under `/etc/ld.so.conf.d` depending on your distribution.

Hi,

I use `nix-shell -p cmake ncurses` to install the nvtop, which does not support `ldconfig -p` (nix does not support it).  Thus, I now manually install it outside nix.  And fixed it.  Thanks!

```
# In nix-shell:

> ldconfig -p
ldconfig: Can't open cache file /nix/store/73k2knwhv4zzizsjr1g1dqjvzkamx8bd-glibc-2.33-49/etc/ld.so.cache
: No such file or directory

# But
> /sbin/ldconfig -p | grep libnvidia-ml
        libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
```

Thanks!
