### ISSUE TITLE
Function keys not working, but displays are

### ISSUE THREAD

**Issue by jpm5830** [Syllo/nvtop#123]
Ubuntu 20.04, I've cloned the repo and built/installed with no warnings or errors. When launched, it works properly except that NONE of the function keys work (see attached screenshot). I have to kill the process manually to exit the app. Note F10, Esc, or q keys will also do nothing. More info below. Any ideas? Thanks, Jim!

![nvidia-smi](https://user-images.githubusercontent.com/68194469/135702675-d00414b0-728a-414c-875d-5de7e15b373e.png)
![screenshot](https://user-images.githubusercontent.com/68194469/135702676-985e64c6-529d-41d9-9699-54e08f60d312.png)

$ nvtop --version
nvtop version 1.2.2
                                                                                                                                                              
$ which nvtop
/usr/local/bin/nvtop
                                                                                                                                                              
$ ldd `which nvtop`
	linux-vdso.so.1 (0x00007ffc4bbac000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f09e7a52000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f09e7a4c000)
	libncursesw.so.6 => /lib/x86_64-linux-gnu/libncursesw.so.6 (0x00007f09e7a12000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f09e79e200
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f09e77f0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f09e7be5000)

$ uname -a
Linux p620 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thesunexpress** [comment]
That would be an issue with your terminal emulator and/or how your keyboard interacts with libinput/evdev. 
Check with xev to see what codes your keyboard(s) send when pressing the various F(n) keys.

**Comment by Syllo** [comment]
Do you get the same issue with other tools based on ncurses, for example htop?

**Comment by jpm5830** [comment]
I installed htop, and it gives the exact same behavior as nvtop. It works, but ignores keyboard. Output from xdev below for F10 and q keys:

KeyPress event, serial 37, synthetic NO, window 0x2a00001,
    root 0x241, subw 0x0, time 600759, (25,-20), root:(76,94),
    state 0x10, keycode 76 (keysym 0xffc7, F10), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2a00001,
    root 0x241, subw 0x0, time 600855, (25,-20), root:(76,94),
    state 0x10, keycode 76 (keysym 0xffc7, F10), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False


KeyPress event, serial 37, synthetic NO, window 0x2a00001,
    root 0x241, subw 0x0, time 584215, (25,-20), root:(76,94),
    state 0x10, keycode 24 (keysym 0x71, q), same_screen YES,
    XLookupString gives 1 bytes: (71) "q"
    XmbLookupString gives 1 bytes: (71) "q"
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2a00001,
    root 0x241, subw 0x0, time 584279, (25,-20), root:(76,94),
    state 0x10, keycode 24 (keysym 0x71, q), same_screen YES,
    XLookupString gives 1 bytes: (71) "q"
    XFilterEvent returns: False

**Comment by jpm5830** [comment]
Solved: Pressing the F10 key on my Ubuntu 20.04 system causes the focus to move outside the nvtop ncurses window (see highlighted screenshot below). Once you click back into the main window following an F10 keypress, all other functions work as expected. To quit, you need to use the Esc key or press 'q' key. 

![Workspace 1_001](https://user-images.githubusercontent.com/68194469/136075743-dfcf6e24-0681-4db1-b8d5-8fb5ddaf73ff.png)

**Comment by joezhouchenye** [comment]
This is not fixed for gnome-termianl on Ubuntu 23.04. Clicking back doesn't work.

**Comment by joezhouchenye** [comment]
This is a keyboard shortcut conflict issue.

In the gnome-terminal configuration, I tried to disable all keyboard shortcuts in the "Keyboard Shortcut" Tab. However, the setting for the F10 key is actually in the "General" Tab. Disabling the menu keyboard shortcut feature there works.
