### ISSUE TITLE
first line disappear after first refresh

### ISSUE THREAD

**Issue by Cinux90** [Syllo/nvtop#126]
Hi everyone,

I installed nvtop from AUR:

```text
Name                     : nvtop
Version                  : 1.2.2-1
Beschreibung             : An htop like monitoring tool for NVIDIA GPUs
Architektur              : x86_64
URL                      : https://github.com/Syllo/nvtop
Lizenzen                 : GPL3
Gruppen                  : Nichts
Stellt bereit            : Nichts
Hängt ab von             : nvidia-utils  ncurses
Optionale Abhängigkeiten : Nichts
Benötigt von             : Nichts
Optional für             : Nichts
In Konflikt mit          : Nichts
Ersetzt                  : Nichts
Installationsgröße       : 91,88 KiB
Packer                   : Felix Yan <felixonmars@archlinux.org>
Erstellt am              : Sa 24 Jul 2021 21:32:58 CEST
Installiert am           : So 05 Dez 2021 14:50:42 CET
Installationsgrund       : Ausdrücklich installiert
Installations-Skript     : Nein
Verifiziert durch        : Signatur
```

But everytime I open after the first refresh the first line will disappear and all the other information will be stay as it is but with one line difference. Maybe this Screenshot will help a bit to understand.
![Terminal Screenshot](https://share.anoxinon.de/f.php?h=2hCmZWR9XXVp7R_qkvp0xa&p=1)

Some information to my system:
```text

 ██████████████████  ████████     cinux@cinux-tower
 ██████████████████  ████████     OS: Manjaro 21.2.0 Qonos
 ██████████████████  ████████     Kernel: x86_64 Linux 5.13.19-2-MANJARO
 ██████████████████  ████████     Uptime: 16h 56m
 ████████            ████████     Packages: 1384
 ████████  ████████  ████████     Shell: bash 5.1.8
 ████████  ████████  ████████     Resolution: 3120x1920
 ████████  ████████  ████████     WM: i3
 ████████  ████████  ████████     GTK Theme: Adapta-Nokto-Eta-Maia [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Papirus-Adapta-Nokto-Maia
 ████████  ████████  ████████     Font: Noto Sans 10
 ████████  ████████  ████████     Disk: 285G / 924G (33%)
 ████████  ████████  ████████     CPU: Intel Core i7-10700F @ 16x 4.8GHz [68.0°C]
 ████████  ████████  ████████     GPU: NVIDIA GeForce RTX 3070
                                  RAM: 2580205568-
```

**Comment by SFMason** [comment]
Same problem here, but from the community repo on vanilla Arch. I've found that the problem only happens when setting sort mode to 'GPU'. Tested each other mode, and they all worked fine. Also, the interface fixes itself when switching off GPU sort to any other sort without needing to restart.

**Comment by Cinux90** [comment]
awesome. Yes this will fix also my problem.

So for everyone you need to set something else under "Processes"->"Sort by". In my case there was "GPU usage" selected. I changed it to Process ID and it works fine.

But this still be an bug at all i would say.

**Comment by Syllo** [comment]
Hey,

I think this has to do with a printf that I mistakingly added while debugging one and got removed in #119.

Does running `nvtop 2>/dev/null` produce the right output?

**Comment by SFMason** [comment]
Yep, that fixes it.

**Comment by Cinux90** [comment]
Yes, this also fixed it for me.
So we need only some day a new release :)
