### ISSUE TITLE
Fresh installaion Ubuntu 20.04 with Nvidia495

### ISSUE THREAD

**Issue by ebeng** [Syllo/nvtop#127]
hi all,

getting the following error:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvtop : Depends: libnvidia-compute-418 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Is NVTOP not able to work with Nvidia-495?

```
:~$ nvidia-smi
Sun Dec 19 21:32:37 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 495.44       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P4000        Off  | 00000000:03:00.0 Off |                  N/A |
| 46%   35C    P8     5W / 105W |      6MiB /  8119MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1147      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

```

**Comment by czarekkwasny** [comment]
I have similar issue on exactly the same driver and Fedora... But the output is "No GPU to monitor."

**Comment by XuehaiPan** [comment]
Build from source will fix this inconsistent dependency. Don't rely on the package manager (`libnvidia-compute-418` vs. `libnvidia-compute-495`).

**Comment by ebeng** [comment]
Just installed it again, but now with CUDA installed primarily -> it works :)


X@x:~$ sudo apt-get install nvtop
[sudo] password for x: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libnvidia-compute-418 libnvidia-compute-430
The following NEW packages will be installed:
  libnvidia-compute-418 libnvidia-compute-430 nvtop
0 upgraded, 3 newly installed, 0 to remove and 8 not upgraded.
Need to get 40.7 kB of archives.
After this operation, 115 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu focal/restricted amd64 libnvidia-compute-418 amd64 430.50-0ubuntu3 [6936 B]
Get:2 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 nvtop amd64 1.0.0-1ubuntu2 [26.8 kB]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  libnvidia-compute-430 495.29.05-0ubuntu1 [6900 B]
Fetched 40.7 kB in 0s (357 kB/s)                                 
Selecting previously unselected package libnvidia-compute-430:amd64.
(Reading database ... 114261 files and directories currently installed.)
Preparing to unpack .../libnvidia-compute-430_495.29.05-0ubuntu1_amd64.deb ...
Unpacking libnvidia-compute-430:amd64 (495.29.05-0ubuntu1) ...
Selecting previously unselected package libnvidia-compute-418:amd64.
Preparing to unpack .../libnvidia-compute-418_430.50-0ubuntu3_amd64.deb ...
Unpacking libnvidia-compute-418:amd64 (430.50-0ubuntu3) ...
Selecting previously unselected package nvtop.
Preparing to unpack .../nvtop_1.0.0-1ubuntu2_amd64.deb ...
Unpacking nvtop (1.0.0-1ubuntu2) ...
Setting up libnvidia-compute-430:amd64 (495.29.05-0ubuntu1) ...
Setting up libnvidia-compute-418:amd64 (430.50-0ubuntu3) ...
Setting up nvtop (1.0.0-1ubuntu2) ...
Processing triggers for man-db (2.9.1-1) ...

**Comment by a-r-j** [comment]
Hi @ebeng, I'm running into this myself. Would you mind clarifying what you mean by installing it with CUDA installed primarily?

**Comment by ebeng** [comment]
Install the Nvidia CUDA driver.
This will uninstall the "normal" Nvidia driver
After this you will be able to install nvtop

**Comment by Syllo** [comment]
Please follow the manual installation for Ubuntu if you are on anything < Ubuntu 22.04.
They have an extra dependency to the Nvidia driver that is not present on other distributions (e.g. Debian).
Similar to https://github.com/Syllo/nvtop/issues/51
