### ISSUE TITLE
Support GeForce GT 71

### ISSUE THREAD

**Issue by 257** [Syllo/nvtop#13]
is this normal?
```
GPU-Util[                                                                             N/A]
MEM-Util[||||||||||||||||||||||||||||||||                                       0.8G/2.1G]
Encoder[                                N/A]
Decoder[                                N/A]
```
```sh
$ nvidia-smi -L
GPU 0: GeForce GT 710
```
```
==============NVSMI LOG==============
Driver Version                      : 410.57
```

**Comment by Syllo** [comment]
I'm not sure that it is supported by the nvml library.
Does the ``nvidia-smi`` command give you more information than what appears in nvtop?

**Comment by 257** [comment]
not really but nvidia-settings does:
```sh
$ nvidia-settings -q GPUUtilization

  Attribute 'GPUUtilization' (zorro:0[gpu:0]): graphics=44, memory=46, video=0, PCIe=1
```

**Comment by Syllo** [comment]
In that case I'm sorry but it will not work better with ``nvtop`` as it uses the nvml library (same as ``nvidia-smi``) to get the GPU information.

I might one day add the support for the "NV-CONTROL-API", which I think is used by ``nvidia-settings``, to support older cards.
