### ISSUE TITLE
Why not ubuntu but nvidia/driver:418.87.01-ubuntu18.04?

### ISSUE THREAD

**Issue by he426100** [Syllo/nvtop#130]
I tried to change nvidia/driver:418.87.01-ubuntu18.04 to ubuntu, the result was successful

**Comment by Syllo** [comment]
Please follow the manual installation for Ubuntu if you are on anything < Ubuntu 22.04.
They have an extra dependency to the Nvidia driver that is not present on other distributions (e.g. Debian).
Similar to #51
