### ISSUE TITLE
MUSL and Nouveau support

### ISSUE THREAD

**Issue by Rabioli** [Syllo/nvtop#131]
I am running void-musl currently, as such no official proprietary driver for nvidia works on my machine, however nouveau seems to be loaded, but I am trying to run a performance test to see if I keep it (even with the awful battery management) or completely unload the module, I intended to use nvtop to have a neat way of looking at it, but it depends on the nvidia proprietary drivers. Could there be a way to use nouveau or to recognize its use in statistics, or would that be too hard and too out of scope to implement?

**Comment by Syllo** [comment]
I will try to look into nouveau at some point.
The main problem is that I don't have access to an NVIDIA GPU anymore.
I'll post updates in #106
