### ISSUE TITLE
Incompatible 510.47.03 with apt installation

### ISSUE THREAD

**Issue by johnnynunez** [Syllo/nvtop#132]
if I install nvtop install driver 470.
New driver not working 510.47.03, with apt installation

![image](https://user-images.githubusercontent.com/22727137/154840702-949a0f17-63e3-49b0-a7d4-0904a6fba150.png)

**Comment by Syllo** [comment]
Please follow the manual installation for Ubuntu if you are on anything < Ubuntu 22.04.
They have an extra dependency to the Nvidia driver that is not present on other distributions (e.g. Debian).
Similar to #51
