### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND. Please set them or make sure they are set and tested correctly in the CMake files: LIBPLIST

### ISSUE THREAD

**Issue by HoangDuc98** [Syllo/nvtop#136]
![2022-03-30_16-53](https://user-images.githubusercontent.com/71063541/160804335-69ba6653-5f9e-406a-8cc7-6216ff2e0bb2.png)

linked by target "airplay" in directory /home/hoang/Downloads/program/UxPlay-master/lib

-- Configuring incomplete, errors occurred!
See also "/home/hoang/Downloads/program/UxPlay-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/hoang/Downloads/program/UxPlay-master/build/CMakeFiles/CMakeError.log".

**Comment by HoangDuc98** [comment]
> ![2022-03-30_16-53](https://user-images.githubusercontent.com/71063541/160804335-69ba6653-5f9e-406a-8cc7-6216ff2e0bb2.png)
> 
> linked by target "airplay" in directory /home/hoang/Downloads/program/UxPlay-master/lib
> 
> -- Configuring incomplete, errors occurred! See also "/home/hoang/Downloads/program/UxPlay-master/build/CMakeFiles/CMakeOutput.log". See also "/home/hoang/Downloads/program/UxPlay-master/build/CMakeFiles/CMakeError.log".

**Comment by HoangDuc98** [comment]
> ![2022-03-30_16-53](https://user-images.githubusercontent.com/71063541/160804335-69ba6653-5f9e-406a-8cc7-6216ff2e0bb2.png)
> 
> linked by target "airplay" in directory /home/hoang/Downloads/program/UxPlay-master/lib
> 
> -- Configuring incomplete, errors occurred! See also "/home/hoang/Downloads/program/UxPlay-master/build/CMakeFiles/CMakeOutput.log". See also "/home/hoang/Downloads/program/UxPlay-master/build/CMakeFiles/CMakeError.log".

**Comment by Syllo** [comment]
This is not UXPLAY. Please open a issue with their project if you cannot compile their source.
