### ISSUE TITLE
Don't require Nvidia related packages when using on a AMD/Intel based system

### ISSUE THREAD

**Issue by Sonickyle27** [Syllo/nvtop#142]
At least using the AUR `nvtop-git` package for Arch Linux, it requires `nvidia-utils` to be installed. On a system with only AMD/Intel hardware, there shouldn't be a need to require any nvidia packages to use nvtop.

This would be really nice to see changed as it turns out KDE Plasma's Wayland session [doesn't play all that well with it on my laptop and causes delays](https://old.reddit.com/r/kde/comments/u5qtjy/when_using_qt_programs_in_wayland_they_have_to/) with program launch speeds :(

**Comment by Syllo** [comment]
Please open an issue or send an email to the maintainer of the AUR package.
I cannot do anything about this issue on my end.

**Comment by Sonickyle27** [comment]
Just to make sure, can nvtop run without that package installed?

**Comment by Syllo** [comment]
Nvtop will load whatever library is installed: libnvml.so for NVIDIA or libdrm.so/libdrm_amdgpu.so for AMD.
If a library is not installed nvtop will just ignore one or the other vendor.

**Comment by Mhowser** [comment]
This is still an issue for us Ubuntu users with AMD only GPUs. I just freshly installed `nvtop` to my system and it gives me the error `Impossible to initialize nvidia nvml : Driver Not Loaded` when I try to use it.

My OS is Zorin OS 16 (which is basically Ubuntu 20.04)

GPU info from `inxi`: 
```
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] driver: amdgpu 
           v: kernel 
           Display: wayland server: X.Org 1.20.13 driver: ati,fbdev unloaded: modesetting,radeon,vesa 
           resolution: 1280x1024~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.41.0 5.13.0-39-generic LLVM 12.0.0) v: 4.6 Mesa 21.2.6
```

**Comment by Syllo** [comment]
@Mhowser for Ubuntu < 22.04 and derivatives, or AMD support, please follow the manual install of the README
