### ISSUE TITLE
GPU reported inconsistently but MEM reports fine

### ISSUE THREAD

**Issue by xM8WVqaG** [Syllo/nvtop#146]
### Important Information

- `nvtop` master ([123908f](https://github.com/Syllo/nvtop/commit/123908faff9c8ff4f8cba5ec7d4ba365c42610fc))
- Ubuntu 22.04
- Kernel 5.15.0-30
- amdgpu
- [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]

### Issue

At the top: GPU is reported as `N/A`, but MEM correctly updates.
Plot: GPU% is always `0`, but MEM% correctly updates.
Table: GPU% updates on individual processes just like MEM% and CPU% values.

See screenshot:

![20220515_00h15m06s_grim](https://user-images.githubusercontent.com/44505331/168452341-1037c514-70e2-4f91-90cc-087201c031e0.png)

It's unexpected that `nvtop` is inconsistently reporting GPU metrics.

**Comment by Syllo** [comment]
Hi @xM8WVqaG,

The information that shows the global GPU usage is extracted from the Linux kernel DRM interface.
The per-process GPU usage is independent and is retrieved from /proc/<pid>/fdifo, introduced in Linux 5.14.

Your GPU being from 2013 I suspect that the DRM interface was not updated while the second one was.

Could you please try the patch (29e0d6968b9694dae9854b8cd196d639ee4e30f0) I pushed to the gpuUsageOldAMD branch to see if it fixes your issue?

To do so:
~~~{.bash}
cd nvtop
git fetch origin
git checkout gpuUsageOldAMD
~~~

and follow the compilation process from the README.

**Comment by xM8WVqaG** [comment]
Fantastic, thanks for the quick turn around! I can confirm your solution means GPU% is now tracked on my hardware.

![20220515_17h27m57s_grim](https://user-images.githubusercontent.com/44505331/168485957-ea57a55a-130a-4228-ac76-aebd47d2afc7.png)
