### ISSUE TITLE
Wrong process ID inside docker

### ISSUE THREAD

**Issue by vio1etus** [Syllo/nvtop#149]
I manually build nvtop in my Ubuntu 20.04 docker container, becuase the driver problem in the pinned issue. However, I found the pid it's showed it's wrong, because I cannot find the pid using `ps`:

![image](https://user-images.githubusercontent.com/33022132/170943658-7c96ab7b-f32c-45cf-9875-fd09dc95a23a.png)
find pid in `ps -aux`
![image](https://user-images.githubusercontent.com/33022132/170943819-977bd4fc-5916-43a1-8517-73003a190371.png)

**Comment by Syllo** [comment]
Hello,

Are you running the compute processes inside containers (docker for example) or WSL?

**Comment by Syllo** [comment]
What I think is happening is that the NVIDIA driver returns the PID on the host which is different than the PID inside the container.

Can you pass options to docker run? Adding "--pid=host" should make it work.

**Comment by vio1etus** [comment]
Thank you very mucn

It does sound like a solution to this problem. However, the behavior of adding `--pid=host` with `docker run` maybe pose potential threats for the host machine, which might be rejected/refused by the administor.

So can you kindly find some other way to make it? If it's too tricky, feel free to close this issue.
Thanks

**Comment by Syllo** [comment]
I'm not sure if it can be retrieved from within the container. There seem to be the same problem for nvidia-smi: https://github.com/NVIDIA/nvidia-docker/issues/1460.

I'll search if docker or the kernel exposes this info in the container.

**Comment by vio1etus** [comment]
Actually, It just because the nvidia-smi problem in container, I searched and found nvtop. 😂
OKOK.  Waiting for your good news.

Best regard.

**Comment by zhuyifei1999** [comment]
The discussion in https://github.com/NVIDIA/nvidia-docker/issues/179 lists two kernel-mode workarounds:
- https://github.com/matpool/mpu
- https://github.com/gh2o/nvidia-pidns

**Comment by Syllo** [comment]
Thank you, @zhuyifei1999.
@vio1etus it may be worth a try to ask your administrator to implement one of the workarounds. Even though they are kernel modules, they are pretty small and can easily be audited.

**Comment by vio1etus** [comment]
> Thank you, @zhuyifei1999. @vio1etus it may be worth a try to ask your administrator to implement one of the workarounds. Even though they are kernel modules, they are pretty small and can easily be audited.

Got it. Thank you very much!
