### ISSUE TITLE
feature request: display time on x axis

### ISSUE THREAD

**Issue by ilemhadri** [Syllo/nvtop#155]
`nvtop` is great - I use it to monitor GPU utilization while running certain interactive tasks.
it would be great if the x axis can display values for time, say in seconds. this would be helpful to have a rough idea of how much time the GPU spent at certain utilization and would make the graph more informative.

**Comment by devalexqt** [comment]
Also, add time collumn in process list, similar to `htop`

**Comment by Syllo** [comment]
@ilemhadri very good idea. I have a first pass on the time_axis branch is you'd like to test.

**Comment by ilemhadri** [comment]
Thanks @Syllo I just checked out the branch

 it looks good to me

I like how the x-axis adapts to the available display size.

**Comment by ilemhadri** [comment]
good for merging to master?

**Comment by Syllo** [comment]
It's now merged into master.

**Comment by Syllo** [comment]
Closing now that this is released.
@devalexqt I opened another issue for the GPU/CPU time as #162. I will probably work on that after the Intel support.
