### ISSUE TITLE
Missing process gpu, enc, dec, gpu mem usage when using 5.19 kernel version

### ISSUE THREAD

**Issue by blae-s** [Syllo/nvtop#158]
**System**:
Kernel: 5.19.0-4-MANJARO arch: x86_64 bits: 64
Desktop: KDE Plasma v: 5.25.4 Distro: Manjaro Linux

**CPU**:
Info: quad core Intel Core i7-4790K 

**Graphics**:
Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] driver: amdgpu v: kernel
Display: x11 server: X.Org v: 21.1.4 with: Xwayland v: 22.1.3 driver: X: loaded: amdgpu unloaded: modesetting,radeon gpu: amdgpu resolution: 1: 1920x1080 2: 1920x1080
OpenGL: renderer: AMD Radeon RX 6600 XT (dimgrey_cavefish LLVM 14.0.6 DRM 3.47 5.19.0-4-MANJARO) v: 4.6 Mesa 22.1.4

Since 5.19 kernel version, as you can see, some data are no longer displayed
![5 19](https://user-images.githubusercontent.com/67500426/183695719-ad824564-34dd-4c1d-88d0-6d0129046e51.png)

Seems to work as expected on 5.15 and 5.18 kernel versions
![5 15_5 18](https://user-images.githubusercontent.com/67500426/183695619-3ba9ed82-5f43-4c84-ae22-832c59bbc785.png)

**Comment by Syllo** [comment]
@blae-s thanks for the report, I'll look into it

**Comment by Syllo** [comment]
I found the issue. With the new kernel, the information exposed in fdinfo changed slightly. I'll push a patch shortly to fix that.

**Comment by Syllo** [comment]
Could you guys please check that the patch on the branch [linux_kernel_5_19_amdgpu_fix](https://github.com/Syllo/nvtop/tree/linux_kernel_5_19_amdgpu_fix) fixes the issue on your side?

**Comment by Mantas-2155X** [comment]
I can confirm that with the above patch, the GPU, Encode, Decode, GPU Memory usages are showing up for all processes now. Linux 5.19.2

**Comment by Syllo** [comment]
Thank you, I merged the patch into master.
I will make a release in the coming week for distros to pull the fix.
