### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Syllo/nvtop#16]
I would like to point out that identifiers like “[`__GET_PROCESS_INFO_H_`](https://github.com/Syllo/nvtop/blob/77ef95489e2e1add95a004bc85e300731e8e5bd0/include/nvtop/get_process_info.h#L22 "Update candidate")” and “[`__INTERFACE_H_`](https://github.com/Syllo/nvtop/blob/bb6239cd24db35f1e65ce5ad5510a8e5bf889fd2/include/nvtop/interface.h#L22 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by Syllo** [comment]
You are right, a bad habit of mine. Fixed in 4377e9c0db95f176f0138705ab8de17b61cf6555.
Thanks

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/Syllo/nvtop/commit/4377e9c0db95f176f0138705ab8de17b61cf6555 "Avoid using reserved C identifiers").
