### ISSUE TITLE
nvtop 2.0.3 not display AMDGPU performance monitoring

### ISSUE THREAD

**Issue by jjk334** [Syllo/nvtop#165]
when I install nvtop2.0.3 in centos7.9，But I can't see the GPU usage of the process。
qemu process use Google emulator + Android7。
![image](https://user-images.githubusercontent.com/77146761/189828767-41c613d3-d63a-453d-a360-203b79edfe6b.png)

**Comment by jjk334** [comment]
Hello,
I reinstall in https://github.com/Syllo/nvtop/archive/refs/heads/master.zip

But the situation is the same
![image](https://user-images.githubusercontent.com/77146761/190401045-d17cd241-3dbb-4a0c-9ca2-283f82e3c39c.png)

**Comment by Syllo** [comment]
Oh, I did not see centos7.9. What is your kernel version?
You can see that with the command `uname -a`

**Comment by jjk334** [comment]
5.11.0

**Comment by Syllo** [comment]
I just verified and the AMDGPU driver first started exposing the per-process information through the fdinfo interface in kernel 5.14 (https://elixir.bootlin.com/linux/v5.14/source/drivers/gpu/drm/amd/amdgpu/amdgpu_fdinfo.c). Hence, you can still see the card usage but won't be able to see the process utilization with your kernel version.

**Comment by Syllo** [comment]
I'll add a note in the README to make that clear.

**Comment by jjk334** [comment]
Does kernel 5.14 or above support amdgpu process monitoring?

**Comment by jjk334** [comment]
when I try kernel 5.15.12.  it dose work! thank you.
![image](https://user-images.githubusercontent.com/77146761/190592991-63ba4e9c-9633-47a9-9238-e05a7fab1833.png)
