### ISSUE TITLE
make appimage format or binary file

### ISSUE THREAD

**Issue by newyorkthink** [Syllo/nvtop#169]
appimage format and binary file format,I can copy on file to everywhere
 
anyone dont to apt-get install nvtop it, 

just download on file to run anywhere ,

it is awesome

can you building

**Comment by Syllo** [comment]
That was the idea when I merged the AppImage related patch :wink: 
Could you try the AppImage from https://github.com/Syllo/nvtop/releases/tag/2.0.4?

**Comment by newyorkthink** [comment]
> That was the idea when I merged the AppImage related patch wink Could you try the AppImage from https://github.com/Syllo/nvtop/releases/tag/2.0.4?

yes it is work,
awesome !!!!!!
