### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [Syllo/nvtop#17]
[The variable “`signal_bits`”](https://github.com/Syllo/nvtop/blob/cb03dd5a2719dc9a24cf838373833621b9beae13/src/nvtop.c#L38 "Update candidate") should [use the data type “`sig_atomic_t`”](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Description for sig_atomic_t usage").

**Comment by Syllo** [comment]
Fixed in fb2e112fb35203a00e87078f577dee2655d517b1 along with the uninterruptible operations ``&= |=``.
Thanks

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Syllo/nvtop/commit/fb2e112fb35203a00e87078f577dee2655d517b1 "Signal handlers: fix uninterruptible operations").
