### ISSUE TITLE
Intel HD Graphics 2000 

### ISSUE THREAD

**Issue by MXH8** [Syllo/nvtop#170]
Running nvtop through the AppImage returns "No GPU to monitor." on a system with an I5-2400 with integrated Intel HD Graphics 2000 running Ubuntu with Kernel 5.4.0-126-generic.

Is this a bug or is nvtop not supposed to detect it?

**Comment by Syllo** [comment]
Hello,

There is currently no release including the Intel support.
I will first finish the patch that adds a setup window to select the GPUs to monitor (through F2) and allow to save this setting.
I will probably do a pre-release later this week with an updated AppImage.

You can either test by compiling the master branch or wait a little bit :wink:

**Comment by MXH8** [comment]
Thanks for the quick reply!

We will test it using the master branch and look forward to the new AppImage :)

**Comment by Syllo** [comment]
Also, please take a look at the Intel section of the README, there are some limitations with old kernels.

**Comment by MXH8** [comment]
Compiling it works and the integrated Graphics get detected as "2nd Generation Core Processor Family Integrated Graphics Controller Integrated GPU". The GPU clock speed is detected correctly, but memory usage and clock, temperature, fan speed, power and percent of GPU utilization are not detected. Very cool that this works already!

**Comment by Syllo** [comment]
Closing for now until the kernel gets better support exposed to the userspace.

**Comment by outusuke** [comment]
I believe the kernel already supports  given that intel_gpu_top is functional. Can we confirm this and provide an update on the GitHub issue?
