### ISSUE TITLE
nvtop fails to run

### ISSUE THREAD

**Issue by ejkitchen** [Syllo/nvtop#174]
nvtop: ./src/extract_gpuinfo.c:205: gpuinfo_populate_process_infos: Assertion `devices[i].processes[j].gpu_memory_percentage <= 100' failed.
 [2]    28194 IOT instruction  nvtop
==========================================================
nvidia-smi works perfectly, pytorch and other cuda app work just fine

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

WSL version: 0.70.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.674

NVIDIA-SMI 520.56.05    Driver Version: 522.25       CUDA Version: 11.8

**Comment by Syllo** [comment]
Hello @ejkitchen,
Thank you for your report. I found the issue with a misplaced assertion.
Feel free to re-open if the issue persists after the fix.

**Comment by ejkitchen** [comment]
I tried to apt update it but I take it the fix is not published via the apt package yet?

**Comment by Syllo** [comment]
Which version are you using?
There is a PPA for Ubuntu with a more recent version: https://launchpad.net/~flexiondotorg/+archive/ubuntu/nvtop
Or you can temporarily use the AppImage of the release that is built without assertions: https://github.com/Syllo/nvtop/releases/tag/3.0.0

**Comment by ejkitchen** [comment]
nvtop version 1.2.2

**Comment by ejkitchen** [comment]
Just upgraded to 

nvtop version 3.0.0

**Comment by ejkitchen** [comment]
Will keep you posted if I get any more errors!

**Comment by allenwu5** [comment]
fixed by this way https://github.com/Syllo/nvtop?tab=readme-ov-file#ubuntu-ppa

**Comment by henryclw** [comment]
> fixed by this way https://github.com/Syllo/nvtop?tab=readme-ov-file#ubuntu-ppa

Thanks a lot, this really works for me. Have a great day!
