### ISSUE TITLE
Assertion failure when trying to only monitor GPU1

### ISSUE THREAD

**Issue by edrutte** [Syllo/nvtop#184]
Hi,
I am running nvtop 3.0.1 (installed via apt) on Debian testing.
kernel: 6.0.12
cpu: Ryzen 9 7950x
gpu0: AMD iGPU
gpu1: Nvidia GTX 1080
nvidia-driver: 510.108.03-1 installed from Debian testing non-free repo

When using the menu to select only one gpu for monitoring it selects gpu0 regardless of the menu selection. When I go back to the menu and select the other gpu it switches to gpu1 but immediately crashes with
```
nvtop: ./src/extract_gpuinfo_amdgpu.c:946: parse_drm_fdinfo_amd: Assertion `!cache_entry_check `&& "We should not be processing a client id twice per update"' failed.
```
The monitoring for gpu1 works correctly while both gpus are selected at once.
If you need any additional system info/logs please let me know.

**Comment by edrutte** [comment]
I upgraded my GPU and this is no longer an issue

**Comment by theoparis** [comment]
This is still an issue with my 6600 xt on debian unstable 👀
