### ISSUE TITLE
Memory ,GPU and Fan usege not showing on Nvidia GeForce GTX 1650

### ISSUE THREAD

**Issue by saha-KUSHAL** [Syllo/nvtop#186]
![image](https://user-images.githubusercontent.com/99195543/211157461-06acd0db-0566-4140-8a66-f5d81d03e0c7.png)

Device- Acer Aspire 7 A715-42g, AMD Ryzen 5500U Processor.
Please let me know if need to submit any log and how i do that.

**Comment by saha-KUSHAL** [comment]
Nvdia driver version- 525.60.11
Os- Pop! OS 22.04 LTS x86_64
Kernel- 6.0.12-76060006-generic (pre installed)
Machine- 64 bit

**Comment by Syllo** [comment]
It seems that you systems is using the AMD GPU by default.
You can see that there is some memory allocated on you NVIDIA GPU (which would show N/A if the information was wrong). This is the case for the FAN, which seems reported as missing by the driver (which I cannot do much about on the nvtop side)

Does the issue persists when you run cuda applications or something on the NVIDIA GPU?

**Comment by saha-KUSHAL** [comment]
Well, it seems like i misunderstood and the usage is showing correctly when running a app with discrete graphics. Another thing is , the ppa version is not detecting amd gpu, only appimage version.
