### ISSUE TITLE
char is unsigned by default on GCC 4,6,7 on ppc64le, breaking the command line options code

### ISSUE THREAD

**Issue by jameshclrk** [Syllo/nvtop#19]
The documentation for `getopt_long` says it returns an `int` (signed) and returns `-1` when there are no more options to parse.

On ppc64le platforms, the `-1` return code gets converted to a `255` causing an infinite loop.

https://github.com/Syllo/nvtop/blob/master/src/nvtop.c#L161-L163

**Comment by Syllo** [comment]
Thank you.
