### ISSUE TITLE
fatal bug when install in docker 

### ISSUE THREAD

**Issue by sliverp** [Syllo/nvtop#199]
docker image is nvidia offical image "nvidia/cuda 11.6.2-base-ubuntu20.04" ,you can repeat this bug easily 

use apt-get to install
`apt-get install nvtop`

then successfully installed.
 but next， nvidia-smi said
`Failed to initialize NVML: Driver/library version mismatch`

next,use `apt-get autoremove nvtop` to uninstall,
nvidia-smi was available again

The bug does not appear every time. sometimes nvtop can be used correctly  for a period of time,and suddenly docker cuda was broken. I have to run a new container from image,and dont know why. But this time this bug occur derectly so i find it.

**Comment by alexander-cheplev** [comment]
Have the same issue. uninstalling as @sliverp mentioned solves the problem.

**Comment by Syllo** [comment]
Yes, Ubuntu 20.04 packaged `nvtop` with a fixed nvidia driver for some reason.
What I would suggest is [build nvtop from source](https://github.com/Syllo/nvtop#nvtop-build), which never had a dependency on a specific nvidia driver whatsoever.

**Comment by Syllo** [comment]
You can also [download the AppImage](https://github.com/Syllo/nvtop#appimage), which does not need any compilation.
