### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by AirVetra** [Syllo/nvtop#2]
~/nvtop/build$ make
[ 20%] Linking C executable nvtop
/usr/lib32/nvidia-390/libnvidia-ml.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
src/CMakeFiles/nvtop.dir/build.make:176: recipe for target 'src/nvtop' failed
make[2]: *** [src/nvtop] Error 1
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/nvtop.dir/all' failed
make[1]: *** [src/CMakeFiles/nvtop.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Syllo** [comment]
I guess that you are on a 64bit system and the first library found was 32bit.
I just pushed a patch that should fix this problem.
Please update to the lastest commit, remove the files in the `build` directory and follow the build step again.

**Comment by AirVetra** [comment]
Thanks, it works!
