### ISSUE TITLE
Problem about "GPU select"

### ISSUE THREAD

**Issue by JiangShanCode** [Syllo/nvtop#201]
When I select "GPU3" and pass F12,
![image](https://user-images.githubusercontent.com/53932468/230380153-f442b609-d41f-45a6-9db4-198bb9390489.png)
it shows the informaton about "GPU0".But it seem refere to "GPU3" after I check.It is confusing. Can the GPU sequence be fixed?
![image](https://user-images.githubusercontent.com/53932468/230380240-40ed36de-4e35-4bd1-8dbb-1c041d440d6a.png)
The version of nvtop is  3.0.1.

**Comment by Syllo** [comment]
You are correct. There was several bugs I introduced and fixed since version 3.0.1 related to GPU select.
It is patched on the master branch but not inside a release yet.

I'll have some time this weekend to work on `nvtop` and will do a release at the same time.
