### ISSUE TITLE
-- Configuring incomplete, errors occurred! See also "/home/me/nvtop/build/CMakeFiles/CMakeOutput.log".

### ISSUE THREAD

**Issue by hasibzunair** [Syllo/nvtop#21]
Getting this error when i run this command 

`cmake ..`

Also tried the latter one in the NVTOP build, but does not work

**Comment by Syllo** [comment]
I cannot deduce your problem without further information.
- Have you installed the prerequisite packages listed in the [build section](https://github.com/Syllo/nvtop#build)?
- Can you please provide the output that ``cmake`` prints on the terminal or the content of the CMakeOutput.log file.

**Comment by hasibzunair** [comment]
I get this:

`hasib@hz:~/nvtop/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- No building type advertised, default to Release
CMake Error at /home/hasib/anaconda3/lib/python3.7/site-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NVML (missing: NVML_INCLUDE_DIRS)
Call Stack (most recent call first):
  /home/hasib/anaconda3/lib/python3.7/site-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindNVML.cmake:52 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:30 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/hasib/nvtop/build/CMakeFiles/CMakeOutput.log".`

**Comment by hasibzunair** [comment]
![screenshot from 2018-10-24 14 06 54](https://user-images.githubusercontent.com/33185386/47415932-6555fb00-d796-11e8-9e65-2036ce32766a.png)

**Comment by hasibzunair** [comment]
[CMakeOutput.log](https://github.com/Syllo/nvtop/files/2509540/CMakeOutput.log)

**Comment by hasibzunair** [comment]
I already have NVIDIA drivers installed. Confirmed by running nvidia-smi

**Comment by Syllo** [comment]
Yes that's the problem of not finding the nvml header (which is not installed with the driver).
So delete everything in the build folder and run cmake again with only

``cmake .. -DNVML_RETRIEVE_HEADER_ONLINE=True``

**Comment by Syllo** [comment]
Almost there,
The executable (``./build/src/nvtop``) and the manual page need to be installed after compilation:
``sudo make install`` in the build directory

**Comment by hasibzunair** [comment]
Worked! Thanks!

![screenshot from 2018-10-24 14 37 32](https://user-images.githubusercontent.com/33185386/47417740-815b9b80-d79a-11e8-81f9-95975f1d4d9f.png)

**Comment by MSathishkumar1990** [comment]
(base) dinesh@dinesh-MS-7B24:~/Pangolin/build$ cmake ..
Build type not set (defaults to release)
-DCMAKE_BUILD_TYPE=Debug for debug
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenGL.cmake:369 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:169 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/dinesh/Pangolin/build/CMakeFiles/CMakeOutput.log".

**Comment by Bahatte** [comment]
Hello i have a same problem... can u help me a little what to do?
