### ISSUE TITLE
Don't power on AMD dGPU

### ISSUE THREAD

**Issue by ChristophHaag** [Syllo/nvtop#211]
When I run nvtop on my laptop with amd iGPU and amd dGPU, the dGPU is powered on, using 8 Watt of power according to nvtop.

It would be nice if nvtop could only monitor the dGPU when it is already powered on so you can monitor your iGPU without wasting battery power.

It would be even nicer if nvtop could allow the dGPU to power off when all other applications using it quit, but I imagine this is a harder problem.

**Comment by Syllo** [comment]
Hello,

You can select which GPU should be monitored through the F2 menu option.
Hence, you can specify not to monitor your iGPU.
