### ISSUE TITLE
is not get show my intel gpu

### ISSUE THREAD

**Issue by newyorkthink** [Syllo/nvtop#214]
![image](https://github.com/Syllo/nvtop/assets/87791643/eea5172d-d594-4722-b05e-135de8b97c82)
MEM N/A MHz TEMP N/A°C CPU-FAN  POW N/A W

**Comment by newyorkthink** [comment]
is need install some package?

**Comment by newyorkthink** [comment]
my os debian

**Comment by Syllo** [comment]
No, unfortunately Intel does not expose as much as AMD and Nvidia at the moment.
I'll close this and track through #197
