### ISSUE TITLE
"GPU Select" menu switches GPUs

### ISSUE THREAD

**Issue by knoffelcut** [Syllo/nvtop#215]
On a Debian Buster PC, using nvtop 3.0.0 from the Focal PPA, the GPU shown are switch from the GPUs I select using F2 -> GPU Select. When manually editing the `~/.config/nvtop/interface.ini` the same GPU is always shown

I have also replicated the same behavior using nvtop 3.0.1 from the AppImage.

The PC has an integrated Intel On-Board GPU and a discrete GeForce GTX 1060. Typically I just want to view the stats for the GTX 1060.

- When selecting the GTX 1060 using the F2 menu, only the Intel GPU is shown.
- When selecting the Intel GPU, only the Nvidia GPU is shown. 

According to `lspci`
```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)
```

When I manually edit `~/.config/nvtop/interface.ini` as follows
```
[Device]
Pdev = 0000:00:02.0
Monitor = false
ShownInfo = gpuRate
ShownInfo = gpuMemRate

[Device]
Pdev = 0000:01:00.0
Monitor = true
ShownInfo = gpuRate
ShownInfo = gpuMemRate
```

Only the Intel GPU is shown, but as shown above the Nvidia GPU was selected. If I switch it around as below

```
[Device]
Pdev = 0000:00:02.0
Monitor = true
ShownInfo = gpuRate
ShownInfo = gpuMemRate


[Device]
Pdev = 0000:01:00.0
Monitor = false
ShownInfo = gpuRate
ShownInfo = gpuMemRate
```

The Intel GPU is correctly selected (but it does not replicate the switching behavior of the menu)

This is all shown in the gif embedded below (hopefully it is going to play, it is not showing in the preview)

![nvtop_device_select_bug](https://github.com/Syllo/nvtop/assets/12249703/9102d435-f729-4073-a015-2179e70a5fde)

**Comment by Syllo** [comment]
Hello.
Could you please try the new release which contains some bug fixes for this and see if the issue persists?

**Comment by knoffelcut** [comment]
Thank you, version 3.0.2 fixed the issue
