### ISSUE TITLE
ENC shows when DEC should with amd graphics

### ISSUE THREAD

**Issue by xcpky** [Syllo/nvtop#218]
When I watch stream or videos in firefox, ENC and its percentage shows, shouldn't DEC show?

**Comment by Umio-Yasuno** [comment]
RDNA 3?

From RDNA 3 (VCN4), the encoding queue and decoding queue have been unified.
The AMDGPU driver handles both decoding and encoding as jobs to the encoding engine.

https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/include/drm-uapi/amdgpu_drm.h?ref_type=heads#L578-581

**Comment by xcpky** [comment]
Yes, my cpu is 7940hs, thx

**Comment by birdie-github** [comment]
@Umio-Yasuno 

Since the pipeline for RDNA 3.0 is now unified could you change the title from `ENC`, to e.g. `VID` (Video Engine) or `ENC/DEC`? People will continue to be confused and will keep on filing bug reports.
