### ISSUE TITLE
Not getting graphs

### ISSUE THREAD

**Issue by modem7** [Syllo/nvtop#22]
Hey, 

I'm running Fedora 25, followed the instructions, but getting the following. Unsure where I've gone wrong?

![capture](https://user-images.githubusercontent.com/4349962/48919228-71160980-ee89-11e8-8a0d-bff72b86b979.JPG)

Thanks!

**Comment by modem7** [comment]
Output of locale:

> LANG=en_GB.UTF-8
> LC_CTYPE="en_GB.UTF-8"
> LC_NUMERIC="en_GB.UTF-8"
> LC_TIME="en_GB.UTF-8"
> LC_COLLATE="en_GB.UTF-8"
> LC_MONETARY="en_GB.UTF-8"
> LC_MESSAGES="en_GB.UTF-8"
> LC_PAPER="en_GB.UTF-8"
> LC_NAME="en_GB.UTF-8"
> LC_ADDRESS="en_GB.UTF-8"
> LC_TELEPHONE="en_GB.UTF-8"
> LC_MEASUREMENT="en_GB.UTF-8"
> LC_IDENTIFICATION="en_GB.UTF-8"
> LC_ALL=

Output of ldd

>         ldd /usr/local/bin/nvtop
>         linux-vdso.so.1 (0x00007ffc4c7f3000)
>         libm.so.6 => /lib64/libm.so.6 (0x00007f72b3493000)
>         libnvidia-ml.so.1 => /lib64/libnvidia-ml.so.1 (0x00007f72b2ebc000)
>         libncursesw.so.6 => /lib64/libncursesw.so.6 (0x00007f72b2c83000)
>         libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f72b2a57000)
>         libform.so.6 => /lib64/libform.so.6 (0x00007f72b2847000)
>         libc.so.6 => /lib64/libc.so.6 (0x00007f72b2481000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007f72b379c000)
>         libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f72b2263000)
>         libdl.so.2 => /lib64/libdl.so.2 (0x00007f72b205f000)
>         libncurses.so.6 => /lib64/libncurses.so.6 (0x00007f72b1e36000)

**Comment by Syllo** [comment]
It seems to be a problem with [putty and ncurses](https://www.suse.com/support/kb/doc/?id=7015165).
Adding ``export NCURSES_NO_UTF8_ACS=1`` to your bashrc or ``NCURSES_NO_UTF8_ACS=1 nvtop`` should hopefully fix it.

If that works I'll add an additional note in the readme.

**Comment by modem7** [comment]
Perfect! 

export NCURSES_NO_UTF8_ACS=1 worked wonders!

Thank you!

**Comment by modem7** [comment]
Perfect! 

export NCURSES_NO_UTF8_ACS=1 worked wonders!

Thank you!
