### ISSUE TITLE
add option to show plots per GPU

### ISSUE THREAD

**Issue by bsdooby** [Syllo/nvtop#23]
Is it possible to show plots for each GPU instead of a summary plot?

**Comment by Syllo** [comment]
Yes, this was my first intention but it still need a bit of work to be usable.

It is also a bit complicated to test because I do not have a multi-GPU setup.

**Comment by Syllo** [comment]
@bsdooby Could you please try the code available in the **dev** branch to see if it works fine for multiple GPUs?

**Comment by Iamanorange** [comment]
![full](https://user-images.githubusercontent.com/6018925/49263625-4d088880-f486-11e8-9db9-0a4e465fe1eb.png)
 Works on large terminal, but:
![half](https://user-images.githubusercontent.com/6018925/49263640-5a257780-f486-11e8-959c-09c2498c85f7.png)
Built on https://github.com/Syllo/nvtop/commit/b5803ff3ce7779f151104cb3133f875eda8745dd .

**Comment by bsdooby** [comment]
@Syllo  Thank you for your quick fix. At first glance (simple tests) this seems to work. @Iamanorange what exactly do you observe? No graphs (re)plotted if resizing the terminal, or no graphs plotted at all in a small terminal?

**Comment by Iamanorange** [comment]
There is one graph plotted for each GPU, but with only one pixel height. So I cannot read anything in the graph.
It happens when the terminal is too small, not when resizing the terminal.

**Comment by Syllo** [comment]
@Iamanorange I see the problem.
I may add a code path to merge multiple graphs together if the size of the plot window is too small.
The problem with this is that with four lines on a single graph it starts to get difficult to read (but still better than a one line graph I suppose).

**Comment by Syllo** [comment]
@Iamanorange Can you please try if it works with the latest version on the master branch?

**Comment by Iamanorange** [comment]
![nvtop](https://user-images.githubusercontent.com/6018925/51105997-87a36600-1825-11e9-9a53-b7576c0b77af.png)
Sorry, I missed the notifications.
Actually I prefer each GPU has its own plot in full screen(1920x1080 and 14pt font size).

**Comment by Syllo** [comment]
No problem, if there is enough vertical space, each GPU will have its own plot.
It is a trade-off to have a better vertical plot resolution (less than 25% per increment) and to deal with many-GPU systems (8-10).

I may add an option to force a plot for individual GPU in the future.
