### ISSUE TITLE
7900xtx not being found

### ISSUE THREAD

**Issue by ewof** [Syllo/nvtop#236]
Ubuntu 22.04.3 LTS
rocm 5.6 installed all the commands like `rocminfo` and `rocm-smi` work etc amdgpu dkms is installed etc
nvtop says No GPU to monitor.

**Comment by supernovae** [comment]
Same problem for me.  

bymiller@byron-X570:~$ rocm-smi --showproductname


============================ ROCm System Management Interface ============================
====================================== Product Info ======================================
GPU[0]		: Card series: 		0x744c
GPU[0]		: Card model: 		0x2422
GPU[0]		: Card vendor: 		Advanced Micro Devices, Inc. [AMD/ATI]
GPU[0]		: Card SKU: 		EXT84765
==========================================================================================
================================== End of ROCm SMI Log ===================================


bymiller@byron-X570:~$ nvtop
No GPU to monitor.
