### ISSUE TITLE
Include GDDR6(X) VRAM temperatures

### ISSUE THREAD

**Issue by Bengt** [Syllo/nvtop#246]
There is now a utility for reading VRAM temperatures under Linux:

<https://github.com/olealgoritme/gddr6>

Include this data in the nvtop, please.

**Comment by hssandriss** [comment]
+1

**Comment by Syllo** [comment]
Looking at the code, it seems that it's directly poking into the kernel memory, which is not something I will implement since it could change at any driver version update and requires root privileges to even get access to.
