### ISSUE TITLE
show CPU utilization

### ISSUE THREAD

**Issue by berleon** [Syllo/nvtop#26]
Hi,

first thanks for this great tool. It really simplifies to keep track of the running GPU processes on our servers. I would also like to also see the CPU utilization. If I would create a pull request, would you welcome this feature?

Thank you, 
Leon

**Comment by Iamanorange** [comment]
Why not use `htop`?

**Comment by Syllo** [comment]
Hi,

I already thought about adding something of the kind, but as @Iamanorange said, the `htop` program (which was the primary inspiration of `nvtop`) is already doing the job.

What would you like to implement? A kind of CPU usage bars?

**Comment by berleon** [comment]
Hi syllo,

of course `htop` does exactly that. However, it is cumbersome to remember the `PID` and then do a lookup in `htop`. Especially, when many processes are running. Therefore, I propose to add a new column `CPU%` between `MEM` and `Command` which display the percentage of CPU usage. It would be exactly the same column as in htop but it would make it a bit more convenient.

**Comment by keybraker** [comment]
The best addition would be a _host cpu usage and memory utilization tab_ **for your cuda proccess** only .

**Comment by Syllo** [comment]
That would be a great idea indeed.

I do not know how to collect these information however. Maybe in `/proc/<pid>/something`.
Looking at how `htop` does it may be the way to go.

@keybraker has a good point.
Maybe should we also consider adding the host residual memory usage?

Either way, I will be glad to accept any advance in that direction.

**Comment by keybraker** [comment]
These two functions return the PID of current process and the PID of parent process respectively.
These can give you the pid for the cpu part of the program. And I guess you can already find the pid of the cuda part. Which means you can get all the data from the current process, even copy code from htop.

```
#include <sys/types.h>
#include <unistd.h>

pid_t getpid(void);
pid_t getppid(void);
```

[FROM LINUX MAN](http://man7.org/linux/man-pages/man2/getpid.2.html)

**Comment by Syllo** [comment]
`/proc/<pid>/stat` seems to be the right file from a fast glance into `man proc`

**Comment by Syllo** [comment]
The last commit on the `dev` branch (a0eaedc2c51e1047d952c6620cb0a692fb7d2c5c) should shows the host processor and memory usage
