### ISSUE TITLE
ENC isn't being shown on graph

### ISSUE THREAD

**Issue by modem7** [Syllo/nvtop#27]
As can be seen in the below graph, GPU and MEM are shown, but the ENC value isn't being plotted.

![capture](https://user-images.githubusercontent.com/4349962/50058901-1a91a780-0177-11e9-87a0-1122b3835018.JPG)

Netdata is showing as follows:

![capture](https://user-images.githubusercontent.com/4349962/50058935-b6bbae80-0177-11e9-951d-1fc92984ad5b.JPG)

**Comment by Syllo** [comment]
Indeed, this is not yes implemented.

**Comment by modem7** [comment]
Closing as this is now part of netdata. No need for this app or issue any longer.
