### ISSUE TITLE
RX 7600 does not display decode bar when decoding videos

### ISSUE THREAD

**Issue by LucasSnatiago** [Syllo/nvtop#277]
I don't know if it is an intended feature (maybe AMD has changed something) or a bug, but everything that uses encoding or decoding on my Radeon RX 7600 displays as encoding even when I'm watching a video.

On Youtube (after enabling decoding via VAAPI on Firefox)
![image](https://github.com/Syllo/nvtop/assets/24521882/da567423-038b-44b6-bdc7-de3d913d28b9)

On MPV when watching my recorded video:
![image](https://github.com/Syllo/nvtop/assets/24521882/1dfc79e2-4d28-4fd3-a235-b58a5d3a80cb)

**Comment by Umio-Yasuno** [comment]
duplicate of #232

**Comment by LucasSnatiago** [comment]
Considering thats a duplicate. I'm going close this issue.
