### ISSUE TITLE
F3 or F2 is not closing the application

### ISSUE THREAD

**Issue by modem7** [Syllo/nvtop#28]
F3 or F2 does not seem to be doing anything in this case. 

When I press either of them, nothing occurs. 

Fedora 25

**Comment by keybraker** [comment]
You have to press **Q** from nvtop/src/nvtop.c line 338
`
case 'q':
        signal_exit = 1;
        break;
`

**Comment by modem7** [comment]
Ah, that certainly works! Thanks!

Looks like the text needs to be modified 

![capture](https://user-images.githubusercontent.com/4349962/50060478-8df1e400-018c-11e9-8b4d-2f66d80ddefc.JPG)

**Comment by Syllo** [comment]
Does the F1 or F2 work for the kill/sort menu? When the menu is active, F3 to quit is not available.
Which terminal emulator are you using?
Escape should also work to quit.

**Comment by modem7** [comment]
Heya - sorry for the late reply!

Neither F1 nor F2 work as expected. 

Using Putty in this case

**Comment by Syllo** [comment]
It seems like a problem with putty / terminal configuration then, see the [similar ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/screen-profiles/+bug/317550).
Try setting the TERM environment variable as putty (`export TERM=putty`) as specified in the [ncurses faq](https://invisible-island.net/ncurses/ncurses.faq.html#xterm_generic).

**Comment by aimuch** [comment]
The F1 is not available.
F1 will pop up the help menu.
I try modify `case KEY_F(1):`->`case KEY_F(9):`, and `case KEY_F(1):`->`case KEY_F(9):`, using F1 replace F1. The F9 works, however, the status bar is stall show F1.

**Comment by Syllo** [comment]
Which help menu are you talking about?
In putty, running the executable as `TERM=putty nvtop` should fix the function key problem.

**Comment by aimuch** [comment]
> Which help menu are you talking about?
> In putty, running the executable as `TERM=putty nvtop` should fix the function key problem.

![nvtop](https://user-images.githubusercontent.com/17581911/51108235-6a25ca80-182c-11e9-9532-3686c6ac7e8d.png)

**Comment by Syllo** [comment]
With #34 and the configuration advice for putty in the `README` 765f355d16b364872d8c681a9b02b965a09688a3 this problem should be resolved.
