### ISSUE TITLE
Error with cmake

### ISSUE THREAD

**Issue by orhanabar** [Syllo/nvtop#30]
> cmake .. -DNVML_RETRIEVE_HEADER_ONLINE=True
> CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
>   Could NOT find NVML (missing: NVML_LIBRARIES) (found version "8")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
>   cmake/modules/FindNVML.cmake:52 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:30 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!

I installed it on AWS without any problem. When I try installing it on server with docker I am using, I got that error.

**Comment by Syllo** [comment]
The error message states that the nvml library is not installed, or installed at a non-standard location.
Did you install the drivers?

**Comment by orhanabar** [comment]
No I didn't install the drivers. I can only modify my docker. What "found version '8'" means?

**Comment by Syllo** [comment]
The library version is extracted from the downloaded header (with `-DNVML_RETRIEVE_HEADER_ONLINE=True`), hence the message "(found version "8")".

The library itself is distributed with the NVIDIA drivers (libnvidia-ml.so), if this library is not installed the error message will be `missing: NVML_LIBRARIES`.

**Comment by Syllo** [comment]
I think that this is fixed by now.
Feel free to re-open if the issue persists.
