### ISSUE TITLE
core dumped Amd gpu 

### ISSUE THREAD

**Issue by amd-maheshs3** [Syllo/nvtop#300]
os: ubuntu 22.04
gpu: amd mi250
no desktop

```py
nvtop: /build/nvtop-0h79qc/nvtop-3.0.0/src/extract_gpuinfo_amdgpu.c:324: initDeviceSysfsPaths: Assertion `gpu_info->hwmonDevice != NULL' failed.
Aborted (core dumped)
```

**Comment by arkhadem** [comment]
Same here. Any solution?

**Comment by arkhadem** [comment]
I built nvtop from the github repo and it works fine.

**Comment by Syllo** [comment]
Hello,
I haven't tested with accelerator cards. Could be that they don't provide an `hwmon` device.
Can you check if #308 fixes this issue?

**Comment by amd-maheshs3** [comment]
it fixed the issue, but not showing process usage other than nvtop.

**Comment by Syllo** [comment]
I can't say for sure because if the accelerator (they are not GPUs right?) does not show the same fdinfo than the graphics driver it won't show up as a process.
