### ISSUE TITLE
Weird characters on display when using AMD GPU.

### ISSUE THREAD

**Issue by Luke20000429** [Syllo/nvtop#304]
I build nvtop from source on a AMD machine. The functionality is OK but the display looks weird.
![image](https://github.com/Syllo/nvtop/assets/45691081/d07eb395-a9c9-498d-8bfd-5f91fae533b4)
Why the border and traces become these letters?

**Comment by Syllo** [comment]
That's the ncurses library falling back to normal characters. Have a look at the [Troubleshooting section](https://github.com/Syllo/nvtop?tab=readme-ov-file#troubleshoot) if you are using Putty or haven't installed the wide version of ncurses.
