### ISSUE TITLE
Issue with make

### ISSUE THREAD

**Issue by jw447** [Syllo/nvtop#31]
After `cmake` in the `build` directory, I had the following error when i make.

>make
make: Warning: File `Makefile' has modification time 25 s in the future
make[1]: Warning: File `CMakeFiles/Makefile2' has modification time 25 s in the future
make[2]: Warning: File `src/CMakeFiles/nvtop.dir/flags.make' has modification time 25 s in the future
Scanning dependencies of target nvtop
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File `src/CMakeFiles/nvtop.dir/flags.make' has modification time 25 s in the future
[ 12%] Building C object src/CMakeFiles/nvtop.dir/nvtop.c.o
[ 25%] Building C object src/CMakeFiles/nvtop.dir/interface.c.o
[ 37%] Building C object src/CMakeFiles/nvtop.dir/interface_layout_selection.c.o
[ 50%] Building C object src/CMakeFiles/nvtop.dir/get_process_info_linux.c.o
[ 62%] Building C object src/CMakeFiles/nvtop.dir/extract_gpuinfo.c.o
[ 75%] Building C object src/CMakeFiles/nvtop.dir/time.c.o
[ 87%] Building C object src/CMakeFiles/nvtop.dir/plot.c.o
[100%] Linking C executable nvtop
**/usr/local/lib/libncursesw.so: could not read symbols: File in wrong format**
collect2: ld returned 1 exit status
make[2]: *** [src/nvtop] Error 1
make[1]: *** [src/CMakeFiles/nvtop.dir/all] Error 2
make: *** [all] Error 2

Can anyone please kindly help?

**Comment by jw447** [comment]
I have following ncurses installed.

```
>rpm -qa | grep ncurse
ncurses-libs-5.7-4.20090207.el6.x86_64
ncurses-5.7-4.20090207.el6.x86_64
ncurses-devel-5.7-4.20090207.el6.x86_64
ncurses-base-5.7-4.20090207.el6.x86_64
```

**Comment by Syllo** [comment]
The "local" part of the location `/usr/local/lib/libncursesw.so` seems suspicious to me.

If you are on CentOS or Red Hat, the library should be located under `/lib64` or `/usr/lib64` from what I see on the CentOS package repository.

Did you install the library with the distribution package manager?

**Comment by jw447** [comment]
I'm on CentOS and I found the library under /lib64 and /usr/lib64 as follows.

'>ls /lib64 | grep 'libncursesw.so'
libncursesw.so.5@
libncursesw.so.5.7*
>: ls /usr/lib64 | grep 'libncursesw.so'
libncursesw.so@`

I don't think the system I'm using have dkpg so I'm gonna guess the ncurse was installed by rpm.

**Comment by Syllo** [comment]
You can try the following to see it it helps.
Go into the `build` directory of nvtop and clean its content.
And try `CMAKE_LIBRARY_PATH="/lib64/" cmake .. && make`

**Comment by Syllo** [comment]
The same but this time with 
`CMAKE_PREFIX_PATH="/usr/" cmake .. && make`
or last option
`CMAKE_PREFIX_PATH="/usr/" CMAKE_LIBRARY_PATH="/lib64/"  cmake .. && make`

Otherwise, I don't see why it prioritizes the local version of the library.
