### ISSUE TITLE
libdrm required on nvidia-only build?

### ISSUE THREAD

**Issue by yapolyak** [Syllo/nvtop#321]
Hi,

I've been trying to build nvtop on a system with Nvidia-only GPU, and I could configure by running
```
cmake .. -DNVIDIA_SUPPORT=ON -DAMDGPU_SUPPORT=OFF -DINTEL_SUPPORT=OFF -DMSM_SUPPORT=OFF
``` 
as without the latter option it was complaining about the lack of `libdrm` which I don't seem to have installed, but nevertheless, when then running `make`, I am getting the header error:
```
.../nvtop/src/extract_gpuinfo_panfrost.c:24:10: fatal error: xf86drm.h: No such file or directory
   24 | #include <xf86drm.h>
      |          ^~~~~~~~~~~
```

So, is `libdrm` mandatory? If not, how to properly run configure?

I was using current `master` branch.

Thanks!

**Comment by Syllo** [comment]
You'll need to disable Panfrost and Pahhor as well: `-DPANTHOR_SUPPORT=OFF -DPANTHOR_SUPPORT=OFF`

**Comment by yapolyak** [comment]
Thank you!
