### ISSUE TITLE
Feature request: watch only a subset of GPUs

### ISSUE THREAD

**Issue by vpuri3** [Syllo/nvtop#323]
Similar to `nvidia-smi -i`. For eg `nvidia-smi -i 1,2` will only show stats for GPUs 1, and 2.

**Comment by Syllo** [comment]
Hello,

On recent version of Nvtop you can press F2 and select the GPUs you want to monitor.
I'm closing this since it's already implemented.

**Comment by vpuri3** [comment]
Thanks for getting back @Syllo. It would be good to have this as a command line option for the following reasons:

1. people with whacky keyboards don't always have function keys, but everybody has access to CLI

2. if i have nvtop running in a small window, the GPU select option is not visible (see screenshot)

![Screenshot 2024-11-04 at 9 33 03 AM](https://github.com/user-attachments/assets/bb76bd63-45d0-41aa-b616-6ddad2e3a37b)
