### ISSUE TITLE
functional enhancement

### ISSUE THREAD

**Issue by frankenstein91** [Syllo/nvtop#39]
Would it still be possible to have the consumed watts drawn in the diagram?
Thank you

**Comment by Syllo** [comment]
Good idea.

I was also thinking of a ways to implement similarly related options for the plot:
  - Limit to one GPU per plot
  - Draw the GPU encode / decode
  - GPU / CPU memory transfer rate

**Comment by Syllo** [comment]
I added an option to display the consumption percentage relative to the maximum power draw returned by the driver.
