### ISSUE TITLE
Prometheus Metrics

### ISSUE THREAD

**Issue by onedr0p** [Syllo/nvtop#40]
Would it be in the scope of the project to have nvtop run as a daemon and have a collector to serve nvidia metrics that Prometheus can consume?

I am imagining a flag `nvtop --daemon --metrics --metrics-port 8000` or something, that would be useful to get the information into Grafana :)

Thanks

**Comment by hyzhak** [comment]
@onedr0p great idea! have you fine any alternative which could do the same things?

**Comment by onedr0p** [comment]
I have forked a repo and updated a few things but I'd rather have it supported in nvtop. It works well currently but updates to the Nvidia drivers could bork things.

https://github.com/onedr0p/nvidia-exporter

**Comment by hyzhak** [comment]
@onedr0p oh, great! Thank you

**Comment by Mart-Bogdan** [comment]
Hello, @onedr0p  your links seems to be dead.

Perhaps you could create Pull Request to this repo?

**Comment by onedr0p** [comment]
Sorry I don't have a need for this anymore and deleted the repo a long time ago.
