### ISSUE TITLE
Incompatible with screen

### ISSUE THREAD

**Issue by lsvih** [Syllo/nvtop#41]
Environment: centOS 7.6

Reproduce: `screen nvtop`

**Comment by Iamanorange** [comment]
Works fine to me.
Ubuntu 16.04

**Comment by lsvih** [comment]
![image](https://user-images.githubusercontent.com/5164225/57190882-1b727c80-6f52-11e9-8822-d63c13bddefc.png)

**Comment by Syllo** [comment]
Hi,
Screen seems fine on Arch Linux too.
Doe it do the same without screen?
It may be a drawing bug, what is the size of the terminal (lines and columns with the command ```stty size```)?

**Comment by lsvih** [comment]
Hi there,
It is working well without screen. `stty size` is `25 80` in screen and terminal.
By the way I find tqdm has same problem in this system, thus it could be a personal configuration issue and couldn't reproduce in other machine.
