### ISSUE TITLE
Cannot open in a stand alone terminal (.desktop file)

### ISSUE THREAD

**Issue by brunoais** [Syllo/nvtop#43]
If I try to create a stand alone instance like htop allows me to.
(htop case: `xfce4-terminal -T "htop" -x /usr/bin/sudo /usr/bin/htop`)
For example, this `.desktop` file (I added the `.txt` so I can upload it):
`Exec=xfce4-terminal -T "NvTop" -x /usr/bin/sudo /usr/bin/nvtop`
[NvTop.desktop.txt](https://github.com/Syllo/nvtop/files/3187446/NvTop.desktop.txt)
nvtop starts and then stops immediately after.

However, it seems to work just fine. If I open a terminal instance and run `nvtop`, nvtop runs as expected. It works both as root and as normal user.
Am I missing something?

**Comment by Syllo** [comment]
Hi,

I am not familiar with xfce but I managed to do that using KDE without a problem with ```konsole -e nvtop``` or ```konsole -e sudo nvtop```, although sudo should only be required to kill non-owned processes.

**Comment by brunoais** [comment]
OK. found the problem. My fail. Wrong path for nvtop. It should have been 
`xfce4-terminal -T "NvTop" -x /usr/bin/sudo /usr/local/bin/nvtop`
`nvtop` is at `/usr/local/bin/nvtop` and not `/usr/bin/nvtop`
