### ISSUE TITLE
nvidia-settings Memory Transfer Rate Double That Shown In nvtop

### ISSUE THREAD

**Issue by rip057** [Syllo/nvtop#44]
just what it says here are two screenshots
![image](https://user-images.githubusercontent.com/10294642/59598867-d4d08000-90c2-11e9-8f6a-257678dc2693.png)
![image](https://user-images.githubusercontent.com/10294642/59598958-05181e80-90c3-11e9-8335-77b32459221e.png)

and again if i lower the power setting...

![image](https://user-images.githubusercontent.com/10294642/59599029-2e38af00-90c3-11e9-8064-67c357d22b7d.png)
![image](https://user-images.githubusercontent.com/10294642/59599044-35f85380-90c3-11e9-9e9e-40c3b4bda8e2.png)

am i missing something here...

also i compiled with the 
    cmake .. -DNVML_RETRIEVE_HEADER_ONLINE=True
fix

**Comment by rip057** [comment]
meh... im guessing it double that datarate is what they are claiming is the max memory rate from the manufacturer...
kinda seems bs for them to advertize the memory rate as 8008 but really it is ddr 4004 or something... because it really is just doubling the lanes...  if this is correct i close this or i will

**Comment by Syllo** [comment]
Hi,

`ntop` uses the `nvmlDeviceGetClockInfo` function which reports the actual memory clock. The transfer rate, which is displayed in the settings, happens to be the double of the clock speed because the gpu uses [double data rate (DDR)](https://en.wikipedia.org/wiki/Double_data_rate) transfers.

It is not a bug, just different information being shown :wink:

**Comment by rip057** [comment]
I kNow this has Nothing to do with this but is there any hope of unlocking
the many many locked booleans that won't allow me to lock the GPU clock, is
this futile?... I mean afterburner can do it in  Windows but I'm fubar in
liNux.  I know all about smi and settings, and know what flags to flip but
they are all locked including the gom.  I'm about to write MSI, as my 1060
is out of warranty maybe they can be nice...
