### ISSUE TITLE
Could NOT find NVML (missing: NVML_LIBRARIES) (found version "10")

### ISSUE THREAD

**Issue by bpinaya** [Syllo/nvtop#45]
Under the lastest Jetpack version 4.2.1 for embedded devices like Xavier or TX2 I'm seeing this issue when trying to cmake:
```
cmake .. -DNVML_RETRIEVE_HEADER_ONLINE=True
```
I get the error:
```
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NVML (missing: NVML_LIBRARIES) (found version "10")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindNVML.cmake:52 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:31 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/nvidia/Documents/nvtop/build/CMakeFiles/CMakeOutput.log".

```
It seems it finds NVML and doesn't find it in the download part where you look for:
```
https://raw.githubusercontent.com/NVIDIA/nvidia-settings/master/src/nvml.h
```
Any insight is appreciated!

**Comment by lamhoangtung** [comment]
I'm having the same issue on Google Cloud Platform Compute Engine

```bash
Cloning into 'nvtop'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 499 (delta 0), reused 1 (delta 0), pack-reused 496
Receiving objects: 100% (499/499), 239.45 KiB | 274.00 KiB/s, done.
Resolving deltas: 100% (303/303), done.
Checking connectivity... done.
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'Release' as none was specified.
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find NVML (missing: NVML_LIBRARIES) (found version "10")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindNVML.cmake:52 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:31 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/hoangviet/linus/nvtop/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

**Comment by Syllo** [comment]
CMake complains because it cannot find the library (libnvml.so file), not the header.
Is the Nvidia proprietary driver installed?

**Comment by rmrao** [comment]
I'm getting the same issue on only one machine (mine says found version "9"). The driver is definitely installed and I can run `nvidia-smi`. I can't figure out what the difference is - I've installed it on two other machines with no problems. It looks like the file is located at `/usr/lib/x86_64-linux-gnu/libnvidia-ml.so` on all my machines.

**Comment by lamhoangtung** [comment]
> I'm getting the same issue on only one machine (mine says found version "9"). The driver is definitely installed and I can run `nvidia-smi`. I can't figure out what the difference is - I've installed it on two other machines with no problems. It looks like the file is located at `/usr/lib/x86_64-linux-gnu/libnvidia-ml.so` on all my machines.

If you have a conda enable. Try to ‘conda deactivate’ first before you make nvtop (even if conda at base environment)

**Comment by rmrao** [comment]
Awesome this worked. I guess my compilers were set to the conda compilers on this one machine. Thanks for the suggestion!

**Comment by Syllo** [comment]
Thank you @lamhoangtung for providing a solution.

I added a comment about **conda** in the README, hopefully this will help.

**Comment by lamhoangtung** [comment]
> Thank you @lamhoangtung for providing a solution.
> 
> I added a comment about **conda** in the README, hopefully this will help.

Thanks ^^. Looks like we can close the issue for now

**Comment by sytelus** [comment]
Here's the full script that takes care of deactivating conda and the reactivating it after install. It would be great to add this in git as something like `install_ubuntu18.sh` so people don't have to keep typing same stuff over and over.

```
sudo apt -y install cmake libncurses5-dev libncursesw5-dev git

# clone if not already exist
[ ! -d 'nvtop' ] && git clone https://github.com/Syllo/nvtop.git
mkdir -p nvtop/build && cd nvtop/build

# if conda environment then first deactivate it
env="${CONDA_DEFAULT_ENV}"
if [[ ! -z "${env}" ]]; then
    conda deactivate

cmake ..

# If it errors with "Could NOT find NVML (missing: NVML_INCLUDE_DIRS)"
# try the following command instead, otherwise skip to the build with make.
cmake .. -DNVML_RETRIEVE_HEADER_ONLINE=True

make
sudo make install # You may need sufficient permission for that (root)

# reactivate conda environment
if [[ ! -z "${env}" ]]; then
    conda activate "${env}"

```

**Comment by andviane** [comment]
For me did not: /bin/sh: 1: conda: not found . The library itself should be installed, because I run sudo apt-get install cuda-nvml-dev-10-1. It is also only on one machine. It can be observed when building on the docker image nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04 that should have all CUDA install (and can run apt-get install cuda-nvml-dev-10-1 without errors).

**Comment by pharpe** [comment]
I'm also getting 
`CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NVML (missing: NVML_LIBRARIES) (found version "10")
`

I have tried `cmake .. -DNVML_RETRIEVE_HEADER_ONLINE=True` and get the same error.  I don't have conda installed.  I also tried running the script that @sytelus posted and get the same error.
Here is the log;
`    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c90] compiler features compiled with the following output:
Change Dir: /home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_d74d5/fast"
/usr/bin/make -f CMakeFiles/cmTC_d74d5.dir/build.make CMakeFiles/cmTC_d74d5.dir/build
make[1]: Entering directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_d74d5.dir/feature_tests.c.o
/usr/bin/cc   -std=c90 -o CMakeFiles/cmTC_d74d5.dir/feature_tests.c.o   -c /home/tom/nvtop/build/nvtop/build/CMake                                                                                                                           Files/feature_tests.c
Linking C executable cmTC_d74d5
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d74d5.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_d74d5.dir/feature_tests.c.o  -o cmTC_d74d5
make[1]: Leaving directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:0c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:0c_variadic_macros
tom@Plex:~/nvtop/build$ clear
tom@Plex:~/nvtop/build$ cat /home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeOutput.log
The system is: Linux - 4.15.0-88-generic - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc
Build flags:
Id flags:

The output was:
0


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is GNU, found in "/home/tom/nvtop/build/nvtop/build/CMakeFiles/3.10.2/CompilerIdC/a.                                                                                                                           out"

Determining if the C compiler works passed with the following output:
Change Dir: /home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_dcf33/fast"
/usr/bin/make -f CMakeFiles/cmTC_dcf33.dir/build.make CMakeFiles/cmTC_dcf33.dir/build
make[1]: Entering directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_dcf33.dir/testCCompiler.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_dcf33.dir/testCCompiler.c.o   -c /home/tom/nvtop/build/nvtop/build/CMakeFiles/CM                                                                                                                           akeTmp/testCCompiler.c
Linking C executable cmTC_dcf33
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_dcf33.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_dcf33.dir/testCCompiler.c.o  -o cmTC_dcf33
make[1]: Leaving directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'


Detecting C compiler ABI info compiled with the following output:
Change Dir: /home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_9f08d/fast"
/usr/bin/make -f CMakeFiles/cmTC_9f08d.dir/build.make CMakeFiles/cmTC_9f08d.dir/build
make[1]: Entering directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9f08d.dir/CMakeCCompilerABI.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_9f08d.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.10/Modules/CMakeCCompile                                                                                                                           rABI.c
Linking C executable cmTC_9f08d
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9f08d.dir/link.txt --verbose=1
/usr/bin/cc     -v -rdynamic CMakeFiles/cmTC_9f08d.dir/CMakeCCompilerABI.c.o  -o cmTC_9f08d
Using built-in specs.
COLLECT_GCC=/usr/bin/cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/sha                                                                                                                           re/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-majo                                                                                                                           r-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --l                                                                                                                           ibexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-boots                                                                                                                           trap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --                                                                                                                           enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-syste                                                                                                                           m-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --w                                                                                                                           ith-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx                                                                                                                           -none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x8                                                                                                                           6_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/:/us                                                                                                                           r/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/:/usr/lib/                                                                                                                           gcc/x86_64-linux-gnu/7/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/..                                                                                                                           /lib/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-rdynamic' '-o' 'cmTC_9f08d' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/7/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -plugin-opt=/us                                                                                                                           r/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccp1VdO2.res -plugin-opt=-pass-through=-lgc                                                                                                                           c -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pas                                                                                                                           s-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -export-dynamic -dynamic-li                                                                                                                           nker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o cmTC_9f08d /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_6                                                                                                                           4-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu                                                                                                                           /7/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/us                                                                                                                           r/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/                                                                                                                           usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. CMakeFiles/cmTC_9f08d.dir/CMakeCCompilerABI.c.o -lgcc --                                                                                                                           push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86                                                                                                                           _64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o
COLLECT_GCC_OPTIONS='-v' '-rdynamic' '-o' 'cmTC_9f08d' '-mtune=generic' '-march=x86-64'
make[1]: Leaving directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'


Parsed C implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command:"/usr/bin/make" "cmTC_9f08d/fast"]
  ignore line: [/usr/bin/make -f CMakeFiles/cmTC_9f08d.dir/build.make CMakeFiles/cmTC_9f08d.dir/build]
  ignore line: [make[1]: Entering directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp']
  ignore line: [Building C object CMakeFiles/cmTC_9f08d.dir/CMakeCCompilerABI.c.o]
  ignore line: [/usr/bin/cc    -o CMakeFiles/cmTC_9f08d.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.10/Modul                                                                                                                           es/CMakeCCompilerABI.c]
  ignore line: [Linking C executable cmTC_9f08d]
  ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9f08d.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/cc     -v -rdynamic CMakeFiles/cmTC_9f08d.dir/CMakeCCompilerABI.c.o  -o cmTC_9f08d ]
  ignore line: [Using built-in specs.]
  ignore line: [COLLECT_GCC=/usr/bin/cc]
  ignore line: [COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper]
  ignore line: [OFFLOAD_TARGET_NAMES=nvptx-none]
  ignore line: [OFFLOAD_TARGET_DEFAULT=1]
  ignore line: [Target: x86_64-linux-gnu]
  ignore line: [Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl                                                                                                                           =file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr                                                                                                                            --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-lin                                                                                                                           ker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nl                                                                                                                           s --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libs                                                                                                                           tdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-                                                                                                                           pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-                                                                                                                           arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offlo                                                                                                                           ad-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux                                                                                                                           -gnu --target=x86_64-linux-gnu]
  ignore line: [Thread model: posix]
  ignore line: [gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) ]
  ignore line: [COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_6                                                                                                                           4-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/]
  ignore line: [LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linu                                                                                                                           x-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-                                                                                                                           gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../:/lib/:/usr/lib/]
  ignore line: [COLLECT_GCC_OPTIONS='-v' '-rdynamic' '-o' 'cmTC_9f08d' '-mtune=generic' '-march=x86-64']
  link line: [ /usr/lib/gcc/x86_64-linux-gnu/7/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -                                                                                                                           plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccp1VdO2.res -plugin-opt=-pas                                                                                                                           s-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -p                                                                                                                           lugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -export-dynam                                                                                                                           ic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o cmTC_9f08d /usr/lib/gcc/x86_64-linux-gnu/7/                                                                                                                           ../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x8                                                                                                                           6_64-linux-gnu/7/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-l                                                                                                                           inux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64                                                                                                                           -linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. CMakeFiles/cmTC_9f08d.dir/CMakeCCompilerAB                                                                                                                           I.c.o -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /u                                                                                                                           sr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o]
    arg [/usr/lib/gcc/x86_64-linux-gnu/7/collect2] ==> ignore
    arg [-plugin] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so] ==> ignore
    arg [-plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper] ==> ignore
    arg [-plugin-opt=-fresolution=/tmp/ccp1VdO2.res] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [-plugin-opt=-pass-through=-lc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [--build-id] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [-m] ==> ignore
    arg [elf_x86_64] ==> ignore
    arg [--hash-style=gnu] ==> ignore
    arg [--as-needed] ==> ignore
    arg [-export-dynamic] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
    arg [-pie] ==> ignore
    arg [-znow] ==> ignore
    arg [-zrelro] ==> ignore
    arg [-o] ==> ignore
    arg [cmTC_9f08d] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o] ==> ignore
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/7] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/7]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/7/../                                                                                                                           ../../x86_64-linux-gnu]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/7/../../../../l                                                                                                                           ib]
    arg [-L/lib/x86_64-linux-gnu] ==> dir [/lib/x86_64-linux-gnu]
    arg [-L/lib/../lib] ==> dir [/lib/../lib]
    arg [-L/usr/lib/x86_64-linux-gnu] ==> dir [/usr/lib/x86_64-linux-gnu]
    arg [-L/usr/lib/../lib] ==> dir [/usr/lib/../lib]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/7/../../..] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/7/../../..]
    arg [CMakeFiles/cmTC_9f08d.dir/CMakeCCompilerABI.c.o] ==> ignore
    arg [-lgcc] ==> lib [gcc]
    arg [--push-state] ==> ignore
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--pop-state] ==> ignore
    arg [-lc] ==> lib [c]
    arg [-lgcc] ==> lib [gcc]
    arg [--push-state] ==> ignore
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--pop-state] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o] ==> ignore
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/7] ==> [/usr/lib/gcc/x86_64-linux-gnu/7]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib] ==> [/usr/lib]
  collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
  collapse library dir [/lib/../lib] ==> [/lib]
  collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/../lib] ==> [/usr/lib]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/7/../../..] ==> [/usr/lib]
  implicit libs: [gcc;gcc_s;c;gcc;gcc_s]
  implicit dirs: [/usr/lib/gcc/x86_64-linux-gnu/7;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib]
  implicit fwks: []




Detecting C [-std=c11] compiler features compiled with the following output:
Change Dir: /home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_cdb64/fast"
/usr/bin/make -f CMakeFiles/cmTC_cdb64.dir/build.make CMakeFiles/cmTC_cdb64.dir/build
make[1]: Entering directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_cdb64.dir/feature_tests.c.o
/usr/bin/cc   -std=c11 -o CMakeFiles/cmTC_cdb64.dir/feature_tests.c.o   -c /home/tom/nvtop/build/nvtop/build/CMake                                                                                                                           Files/feature_tests.c
Linking C executable cmTC_cdb64
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cdb64.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_cdb64.dir/feature_tests.c.o  -o cmTC_cdb64
make[1]: Leaving directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:1c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c99] compiler features compiled with the following output:
Change Dir: /home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ce7dd/fast"
/usr/bin/make -f CMakeFiles/cmTC_ce7dd.dir/build.make CMakeFiles/cmTC_ce7dd.dir/build
make[1]: Entering directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ce7dd.dir/feature_tests.c.o
/usr/bin/cc   -std=c99 -o CMakeFiles/cmTC_ce7dd.dir/feature_tests.c.o   -c /home/tom/nvtop/build/nvtop/build/CMake                                                                                                                           Files/feature_tests.c
Linking C executable cmTC_ce7dd
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ce7dd.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_ce7dd.dir/feature_tests.c.o  -o cmTC_ce7dd
make[1]: Leaving directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c90] compiler features compiled with the following output:
Change Dir: /home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_d74d5/fast"
/usr/bin/make -f CMakeFiles/cmTC_d74d5.dir/build.make CMakeFiles/cmTC_d74d5.dir/build
make[1]: Entering directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_d74d5.dir/feature_tests.c.o
/usr/bin/cc   -std=c90 -o CMakeFiles/cmTC_d74d5.dir/feature_tests.c.o   -c /home/tom/nvtop/build/nvtop/build/CMake                                                                                                                           Files/feature_tests.c
Linking C executable cmTC_d74d5
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d74d5.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_d74d5.dir/feature_tests.c.o  -o cmTC_d74d5
make[1]: Leaving directory '/home/tom/nvtop/build/nvtop/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:0c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:0c_variadic_macros
`

**Comment by snafu123** [comment]
i see this too

**Comment by eriksneff** [comment]
@pharpe I'm seeing the same thing. I'm on a stock install on the jetson xavier mx dev kit board. I don't have conda installed. Just looking for a quick way to montior gpu utilization as I test transcoding performance. Frustrating.

**Comment by Syllo** [comment]
The only thing I can think of at this point is adding more hints for CMake.

Can you please try with the version on the branch `cmake_nvml_notfound`.

If this does not work, can you please provide the path where the library is located and I will add it to the hint list.

**Comment by pharpe** [comment]
Removed the old git clone
```
sudo rm -rIf nvtop
```
cloned the cmake_nvml_notfound branch
```
git clone -b cmake_nvml_notfound --single-branch https://github.com/Syllo/nvtop.git
```
Created the build directory and cd to it
```
mkdir -p nvtop/build && cd nvtop/build
```
Ran cmake
```
user@server:~/nvtop/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'Release' as none was specified.
-- Could NOT find NVML (missing: NVML_INCLUDE_DIRS NVML_LIBRARIES)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NVML (missing: NVML_INCLUDE_DIRS NVML_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindNVML.cmake:52 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:33 (find_package)
```

**Comment by Syllo** [comment]
Thanks @pharpe, is your `libnvidia-ml.so` library installed in one of the following directories?  /usr/lib64/nvidia*/ /usr/lib/nvidia*/ /usr/lib/*linux-gnu

**Comment by benroeder** [comment]
I am having the same issue,  libnvidia-ml.so is installed in
/usr/local/cuda-10.2/targets/aarch64-linux/lib/stubs/libnvidia-ml.so

**Comment by Mistobaan** [comment]
fixed with my patch https://github.com/Mistobaan/nvtop#master and adding. This washappening building from an nvidia TensorRT container

```
cmake .. \
    -DNVML_INCLUDE_DIRS=/usr/local/cuda-10.1/targets/x86_64-linux/include/ \
    -DNVML_LIBRARIES=/usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/libnvidia-ml.so
```

**Comment by Syllo** [comment]
Close as we don't rely on the nvml header anymore.
