### ISSUE TITLE
error: unknown type names ‘nvmlDevice_t’, 'nvmlProcessInfo_t'

### ISSUE THREAD

**Issue by JeffreyUrban** [Syllo/nvtop#49]
Following the instructions to build for Ubuntu 18.04.3 with (NVIDIA-SMI 440.26, Driver Version: 440.26), while running make, the build fails with errors:

... /nvtop/include/nvtop/extract_gpuinfo.h:76:3: error: unknown type name ‘nvmlDevice_t’
... /nvtop/include/nvtop/extract_gpuinfo.h:108:3: error: unknown type name ‘nvmlProcessInfo_t’

Potentially related information:

cmake reported:
CMake Warning (dev) at cmake/modules/FindNVML.cmake:45 (message):
  Unable to find nvml api version

libnvidia-ml components are here:
$ ldconfig -p | grep nvidia-ml
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
	libnvidia-ml.so.1 (libc6) => /usr/lib/i386-linux-gnu/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
	libnvidia-ml.so (libc6) => /usr/lib/i386-linux-gnu/libnvidia-ml.so

**Comment by JeffreyUrban** [comment]
I found that `nvtop/build/include/nvml.h` was an empty file.

I removed and re-cloned the project and built again. This time I ensured that conda was deactivated beforehand. Now with `cmake ..`, I see the `Could NOT find NVML (missing: NVML_INCLUDE_DIRS)` error.

Unfortunately, `cmake .. -DNVML_RETRIEVE_HEADER_ONLINE=True` just hangs with no output.

**Comment by Syllo** [comment]
Hi Jeffrey,

If the header is always empty, and the download with `-DNVML_RETRIEVE_HEADER_ONLINE=True` seems to hang you can try providing the header ([which can be dowloaded from the nvidia-settings github repo](https://raw.githubusercontent.com/NVIDIA/nvidia-settings/master/src/nvml.h)) at the location `nvtop/build/include/nvml.h` and try a build without the `NVML_RETRIEVE_HEADER_ONLINE` option set.

I am not sure why CMake struggles to download this file though.
Do you have `curl` installed? (I suppose that CMake requires it to download from URL)

**Comment by EsmeraldaQuintero** [comment]
During cmake I got:
```
-- Found NVML: /home/user/Desktop/nvtop/build/include  
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncursesw.so
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncursesw.so - found
-- Found Curses: /usr/lib/x86_64-linux-gnu/libncursesw.so  
```
But during make I got:
```
In file included from /home/user/Desktop/nvtop/include/nvtop/interface.h:25:0,
                 from /home/user/Desktop/nvtop/src/nvtop.c:32:
/home/user/Desktop/nvtop/include/nvtop/extract_gpuinfo.h:76:3:
error: unknown type name ‘nvmlDevice_t’
nvmlDevice_t device_handle;
^
```
And another nv* errors

**Comment by phoenixmy** [comment]
same problem with above comments.
at last, I copy the nvml.h manually from  /usr/local/cuda-10.0/include to build/include
and everything goes well.

maybe you can try, good luck!


$cmake .. -DNVML_RETRIEVE_HEADER_ONLINE=True
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'Release' as none was specified.
-- Found NVML: /usr/local/cuda-10.0/include (found version "10") 
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncursesw.so
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncursesw.so - found
-- Found Curses: /usr/lib/x86_64-linux-gnu/libncursesw.so  
-- Performing Test compiler_has-Wall

**Comment by Syllo** [comment]
The header is not required anymore to compile the latest version of nvtop.
