### ISSUE TITLE
Can't scroll/view offscreen processes

### ISSUE THREAD

**Issue by dd-dent** [Syllo/nvtop#5]
I have a server running something one the order of 80 GPU processes spread across 8 GPU's.  
The issue is  I can't scroll the process list beyond the first visible one's(14 on my MBP's screen).  
P.S.  
Built from latest commit in dev.

**Comment by Syllo** [comment]
Hi
Yes the scrolling was not implemented yet.
I have pushed the code that should add this capability on the `dev` branch.
Can you please give it a try?

**Comment by dd-dent** [comment]
Just checked and it works fine, although the scrolling itself is a little bit sluggish compared to htop for some reason...
Thanks!
