### ISSUE TITLE
Not issue but feature question

### ISSUE THREAD

**Issue by AirVetra** [Syllo/nvtop#50]
I've found option to select or ignore some GPUs, but the bar-plot still draws two main GPUs charts on one plot.

I've 3 GPUs - 1 710 (device 0) to connect to monitor and draw X-server and two more 1080ti (devices 1 and 2) for DS calculation. 
With default "htop" run - we have two plots - one for both 1080ti on one chart and one for not needed 710.
When i run "htop -i 0" it selects right GPUs but still draws only one plot with both 1080ti on it.

Is it possible to have two separate graphs for GPU 1 and GPU 2?

Thanks!

**Comment by Syllo** [comment]
Hi,

Unfortunately it is not possible to have two separate graphs for the moment.
It was already pointed out in #39 but is still in the TODO list.

**Comment by Syllo** [comment]
The latest version should display one chart per device if there is enough room in the terminal.
