### ISSUE TITLE
CPU usage calculation wrong

### ISSUE THREAD

**Issue by Zonicwenlock** [Syllo/nvtop#56]
Hi, i use nvtop 1.0.0 on Ubuntu 18.04.03 and Nvidia 440.33.01.
While Rendering on the GPU with Blender 2.82 i found this gpu usage of 991%
![nvtop](https://user-images.githubusercontent.com/61094121/74594641-f494bb00-5038-11ea-818d-9dca46c8aa41.png)

CPU is a Ryzen 5 2600x

**Comment by pmeier-tiplu** [comment]
Wanna sell that particular card?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Zonicwenlock** [comment]
Why? you can buy it everywhere for < 200€

**Comment by Syllo** [comment]
Hi,

Can you please check what htop (or top) reports in CPU usage for the same process?

Your CPU has up to 12 threads. Hence, if your application is multi-threaded, it can show a percentage up to 1200% (100% is per-CPU).
