### ISSUE TITLE
Gen1@16x

### ISSUE THREAD

**Issue by AirVetra** [Syllo/nvtop#6]
Device 0 [GeForce GTX 1080 Ti] PCIe GEN 3@16x 
Device 1 [GeForce GTX 1080 Ti] _**PCIe GEN 1@16x**_ 

but we know it works at GEN 3

**Comment by Syllo** [comment]
If the GPU is idle it may use a lower link generation (probably to reduce power consumption).
Only the current gen and link width are displayed, not the maximum ones available to the GPU.

Did you look when there is at least one active task on the GPU or when it was idle ?
