### ISSUE TITLE
ENC percentage, what it is?

### ISSUE THREAD

**Issue by sonic182** [Syllo/nvtop#62]
Yes I know is not an issue

I'm converting a video with ffmpeg and h264_nvenc encoder (nvidia encoder) and I'm having ENC close to 100%

This is Encoder usage % isn't it?

I'm asking because there is no explicit reference/documentation...

**Comment by Syllo** [comment]
Hello,
Yes, two new meters appear only when used by the GPU, the encoder (ENC) and decoder (DEC).
Thank you for pointing at the lack of documentation, I'll add that to the manpage.

**Comment by Syllo** [comment]
Added to the manpage in 22a726942b9acfb01fa3af491b47dac5d320cb12.
