### ISSUE TITLE
Feature Request: Add batch mode / CLI usage

### ISSUE THREAD

**Issue by saravanabalagi** [Syllo/nvtop#64]
Is it possible to add a simple CLI to retrieve usages for logging and/or piping into other programs similar to top? Something like `batch_mode -b` for top

Example: 
```sh
nvtop -b -o gpu_mem -o host_mem
# Output
2221MB 2863MB
```

**Comment by gothicVI** [comment]
That can already be done using `nvidia-smi`. You might want to look into that.

**Comment by NRevathi** [comment]
I tried... but getting errors..

$nvtop -b -o gpu_mem -o host_mem
Unhandled error in getopt missing argument
$

**Comment by gothicVI** [comment]
@NRevathi That's not supported (did you even fully read the two posts above yours?).
That's actually what this request is about.

You can get the information you're looking for via `nvidia-smi`.

**Comment by saravanabalagi** [comment]
@gothicVI, thanks for your reply. I'm aware that `nvidia-smi`'s CLI can be used to get values, and they also offer to format them as csv with or without units like

```sh
nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader
# Output
1 %
```
But how do I get `CPU%` and `Host Mem` from what's shown in `nvtop`? I can do `ps -p <pid>` but there many problems around that. One, it gives total cpu usage / elapsed time for pid, two, both memory and cpu % will be only for that PID, `nvstat` treats that process and all it's children as one and shows cpu and memory occupied for the process tree.

**Comment by NRevathi** [comment]
Thanks a lot.

Tried the following command for short-term logging..
I think script is required to capture the data in .csv dynamically and tune the frequency.


$ **nvidia-smi --query-gpu=power.draw,temperature.gpu,utilization.gpu,clocks.gr,clocks.sm --format=csv,noheader,nounits -l 1 >> out.csv**
^Z
[18]+  Stopped                 nvidia-smi --query-gpu=power.draw,temperature.gpu,utilization.gpu,clocks.gr,clocks.sm --format=csv,noheader,nounits -l 1 >> out.csv
$ **cat out.csv
3.10, 43, 1, 300, 300
2.92, 43, 1, 300, 300
2.88, 43, 1, 300, 300
2.96, 43, 1, 300, 300
2.89, 43, 0, 300, 300**
$

**Comment by NRevathi** [comment]
I use another tool called CoreFreq to get CPU information.

Thank you.

**Comment by Syllo** [comment]
Hello,

Thank you for helping @saravanabalagi.

Considering that the nvidia-smi tool provides a CSV interface, I will not implement the same feature myself but would consider a merge request.
