### ISSUE TITLE
Graph direction is backward...

### ISSUE THREAD

**Issue by larrybrit** [Syllo/nvtop#69]
Hello, the graph history seems to  read backward? New data enters from the left instead of the right as it is on every other monitoring app.

**Comment by Syllo** [comment]
Hello,
I see. Maybe everyone else is doing it wrong then :wink:
On the timeline left is the most recent and right is the oldest.
I didn't really think it through, but I might change this and/or add an option to reverse it.

**Comment by larrybrit** [comment]
That would be great!

**Comment by JennyLouise** [comment]
I'd appreciate that too, most other graphs plot from left to right with the most recent on the right hand side. It would make it easier to read and easier to compare to other graphs.
