### ISSUE TITLE
PID shown by nvtop differs from the one shown by htop

### ISSUE THREAD

**Issue by danielracz** [Syllo/nvtop#70]
Dear Syllo,

I created a very simple python script to allocate some GPU memory - the corresponding process appeared in nvtop:
![image](https://user-images.githubusercontent.com/22894148/83689797-f4242e00-a5ef-11ea-9263-58fbc2e580c6.png)
However, the PID I can see using htop differs from that one:
![image](https://user-images.githubusercontent.com/22894148/83689969-3483ac00-a5f0-11ea-8286-ef1ca0d8b2f7.png)

Do you happen to have any idea? Please note, that this can be a driver related issue as in the output of nvidia-smi there are no processes shown at all. I tried to find some answers for this one as well, but the only thing I found is that in containers it won't work. However, I do not use any containers and I don't have root access either, hence driver updates are not really possible.

Thanks in advance for any advice,
Daniel

**Comment by Syllo** [comment]
Maybe the python runtime/library you are using spawns a sub-process to manage cuda? If so, you should be able to see that while using the tree view of htop (by pressing F5).

What I don't understand is that you should observe the same output from nvidia-smi.

**Comment by gothicVI** [comment]
Can you share the script?
I'd like to take a look at that as well.

**Comment by danielracz** [comment]
I checked the subprocesses, but none of them has the same PID (not even close if that matters) as the one in the nvtop output. The output of nvidia-smi looks like this:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Graphics Device     Off  | 00000000:0B:00.0 Off |                  N/A |
| 40%   42C    P8    31W / 280W |  11027MiB / 24190MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Graphics Device     Off  | 00000000:11:00.0 Off |                  N/A |
| 41%   43C    P8     4W / 280W |    781MiB / 24190MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

The memory usage is the same as shown in nvtop, but as you can see, processes are not shown here (that's why I started to search for another solution and found nvtop). 

The script I'm using for testing:
```
import torch
import time

a = torch.ones(100000, device = "cuda:0")
time.sleep(500)
```

**Comment by kaerka** [comment]
I think that you have a driver issue - possibly also not running the nvidia-persistence daemon?  I tested this (in a gpu-enabled docker container), and was able to see the python process in both nvidia-smi and nvtop.
![nvtop-torch-python](https://user-images.githubusercontent.com/1696060/84697855-db374900-af1c-11ea-9016-992a7d05463f.PNG)

**Comment by philipl** [comment]
This is due to setting `NVML_NO_UNVERSIONED_FUNC_DEFS`. If I remove this definition, then the pids are correct. It has to do with the v2 vs not-v2 of the function that gets the process information. Not well documented on nvidia's side.

**Comment by Syllo** [comment]
@philipl, I see, I applied the patch that adds this definition for the set of people download the nvml library header (which is not installed on every distributions for some reason) and having an older driver version that lacks the new function versions. The compilation would fail for them while linking the executable.

I don't know why NVIDIA created new versions of these functions that way, with the same prototype and "overload using macros", instead of patching the old function directly.

I think that I could set a test in CMake to check if the compilation would succeed without the definition and define it otherwise.
This should fix the issue on systems with up to date drivers.

**Comment by aahouzi** [comment]
Hi guys! I have the exact same issue with nvtop, when I train my models i have memory which is not freed, and processes shown in nvtop, but not in htop or top for example. You said it's due to setting the variable NVML_NO_UNVERSIONED_FUNC_DEFS, where can I find this variable, and what should I change about this variable so i can kill the processes that are still running? 

Thanks in advance u for ur answer :)

**Comment by Syllo** [comment]
Hi,

Have you tried with the version of nvtop present on the master branch as of yesterday?

This version should fix the problems like these by loading the latest version of the library functions, no need for NVML_NO_UNVERSIONED_FUNC_DEFS anymore.

**Comment by Erotemic** [comment]
I have a similar issue where nvtop shows a zombie process, but nvidia-smi doesn't. I was wondering if there was a way for nvidia-smi to list it as well (as I'd like to automate the cleanup of zombies).

E.g.

![image](https://user-images.githubusercontent.com/3186211/222919631-4b0ecefd-3ec6-4e6d-8a9a-341d115d6a8f.png)

3591263 is a zombie

but nvidia-smi doesn't show it

```
Sat Mar  4 12:16:19 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 30%   51C    P0   113W / 370W |    644MiB / 24265MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:03:00.0 Off |                  N/A |
| 32%   33C    P8    32W / 350W |  22259MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2664      G   /usr/lib/xorg/Xorg                288MiB |
|    0   N/A  N/A   3298134      G   ...Y5NDVkZDZl&browser=chrome       43MiB |
|    0   N/A  N/A   3532680      G   .../debug.log --shared-files        4MiB |
|    0   N/A  N/A   3532681      G   ...veSuggestionsOnlyOnDemand        4MiB |
|    0   N/A  N/A   3556080      G   /usr/bin/gnome-shell              104MiB |
|    0   N/A  N/A   3621962      G   ...465197132669750018,131072      120MiB |
|    1   N/A  N/A      2664      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```


Futhermore, `nvidia-smi pmon -s m -c 1` doens't show it either:

```
# gpu        pid  type    fb   command
# Idx          #   C/G    MB   name
    0       2664     G   288   Xorg           
    0    3298134     G    43   join?action=joi
    0    3532680     G     4   debug.log --log
    0    3532681     G     4   Slack --gpu-pre
    0    3556080     G    97   gnome-shell    
    0    3621962     G   102   chrome --type=g
    1       2664     G     4   Xorg           
```

**Comment by XuehaiPan** [comment]
> And is there a way I can get it with nvidia-smi or some other programatic way?

@Erotemic `nvidia-smi` filters out the zombie and terminated processes when it got errors in `nvmlSystemGetProcessName`. So you cannot find them by `nvidia-smi --query-gpu=...`.

You can find the raw PIDs by `nvmlDeviceGetComputeRunningProcesses` and `nvmlDeviceGetGraphicsRunningProcesses`.

Ref:

- Go: [go-nvml](https://github.com/NVIDIA/go-nvml)
- Python: [nvidia-ml-py (pynvml)](https://pypi.org/project/nvidia-ml-py), [gpustat](https://github.com/wookayin/gpustat), [nvitop](https://github.com/XuehaiPan/nvitop)

**Comment by personaco** [comment]
check that your notebook (load model and save it to cache....) opend
