### ISSUE TITLE
Feature request: update rate and same color for mem/util

### ISSUE THREAD

**Issue by cgebbe** [Syllo/nvtop#72]
I highly appreciate the tool, thank you so much.

Two ideas for even further improvement
1. The update rate of the charts seems fixed (every 1s?). Could we add a parameter similar to "-l" in nvidia-smi to change this?
2. In our case, there are two GPU's per chart, which is fine. However, since both the mem and the utilization are plotted, there are four lines with different colors, which becomes confusing quickly. As an alternative: Can we add a parameter to disable the memory plot? Or can we plot mem and util from one GPU in the same color, but one as a solid line, the other as a dotted line?

Cheers

**Comment by timstd** [comment]
I agree! Being able to change the update rate of the chart would be really useful

**Comment by Syllo** [comment]
The update rate can be changed in the interface setup menu (F2) or using the ``-d`` command line option.
You can also choose which metrics to display.
