### ISSUE TITLE
Not pretty look on CentOS 7.8.2003

### ISSUE THREAD

**Issue by gavrin-s** [Syllo/nvtop#75]
I don't get a pretty look on CentOS 7.8.2003(`q`, `x` instead `_`, `|`). What could be the reason?
![image](https://user-images.githubusercontent.com/15730417/91421310-fa891580-e87f-11ea-8ba9-12efed56a409.png)

**Comment by Syllo** [comment]
Hello,

It is related to the ncurses library which is used to draw the interface.

On CentOS it should have been installed with the ncurses-devel package (you can check that the nvtop executable links to it with the `ldd /path/to/nvtop`).

My guess is that the curses library cannot identify your terminal capabilities and falls back to plain old ascii.
If you are using putty to connect to the server, see the troubleshoot section in the README.

**Comment by gavrin-s** [comment]
Hi! Restart fix my problem)
