### ISSUE TITLE
feature request: add nvtop feedstock to conda-forge

### ISSUE THREAD

**Issue by AndrewAnnex** [Syllo/nvtop#76]
It would be great if nvtop could be installed/compiled using the conda-forge to allow easy integration into conda environments and for users without root permissions. I know it is actually relatively easy to build nvtop without this, but I also just want the even easier solution out there for myself and others

**Comment by hmaarrfk** [comment]
Not seeing this, i was building it for myself.

https://github.com/conda-forge/staged-recipes/pull/19330

I think alot of the work decoupling the dependency at build time on cuda has helped. I'll see if i can make an issue to cleanup the documentation.

**Comment by matthiasdiener** [comment]
nvtop is available here: https://github.com/conda-forge/nvtop-feedstock

**Comment by matthewfeickert** [comment]
Ah this is amazing! Thank you so much @hmaarrfk and @matthiasdiener! I was just looking to open an Issue as this isn't mentioned in the ["Distribution Specific Installation Process" section of the README](https://github.com/Syllo/nvtop/blob/20ea55dbd1eeb4342ff0112fae3ee2a0bfe352ea/README.markdown#distribution-specific-installation-process) and then I found this Issue.

It is so nice to be able to

```
pixi global install nvtop
```

and then have the latest `nvtop` ready to go! :rocket:

**Comment by hmaarrfk** [comment]
Yeah. I've been using it for a while and it's great because Ubuntu's pinning a for it clashes when you upedate the Nvidia driver. It has been really great for performance monitoring.
