### ISSUE TITLE
Is it possible to make windows support?

### ISSUE THREAD

**Issue by metya** [Syllo/nvtop#77]
I've using this tool in my manjaro distr.

But for windows, there is no such cool tool for retrive information about GPU utilization. 

So maybe is it not hard to port this to windows platform?

I tried to build it from scratch, but get the nvml not found library error with (found version "11"). Seem to online header flag finds the library, but not loaded it, cause it don't know where in windows nvml.dll library and of course due to there is no code for load dll files. 

So I thought it is not much complicated to make support windows. I don't know. 
But windows users would appreciate for that.

**Comment by Syllo** [comment]
Hello,

Firstly, I may be wrong, but starting with Windows 10, the task manager should be able to show the GPU utilization.
It may not show it by default though and can be enabled by a setting.

Secondly, concerning a Windows port of nvtop, it could be done providing the following contributions:

- The functions present in the file `src/get_information_linux.c` need to be ported to Windows.
- The CMake files need to be updated for Windows support.

Unfortunately I do not have access to a computer under Windows and equipped with an Nvidia GPU, nor am I accustomed with Windows system development.

I will gladly merge patches for Windows support, but I do not plan to do that myself until I need it myself.

**Comment by metya** [comment]
Thank you for your answer!

It is correct that the windows task manager can show the GPU utilization, but this way not so convenient as the CLI utility and not so precise I think. But ok! I should use that.

**Comment by Syllo** [comment]
Another way that I didn't think of is using the Linux subsystem for Windows, but I never used it and don't know if it is easy to compile nvtop in it.

If you are lucky it may "just work".

**Comment by metya** [comment]
Yeah, I thought about that. But it is hard to forward GPU through WLS. In WLS2 it could do, and perhaps I'll try.
