### ISSUE TITLE
Power not shown for RTX 2060 Mobile

### ISSUE THREAD

**Issue by Cherenkov11** [Syllo/nvtop#79]
Whenever I use nvtop the power usage is not shown properly, even though nvidia-smi show it "correctly", here is a screenshot of the behavior: (I said "correctly" because the cap value is not reported by nvidia-smi, maybe because this is mobile card or some bug on the nvidia driver, but the usage value is reported correctly). Fans are also not reported, but I think that is because of the laptop implementation, since them are not controlled by the nvidia driver.

![image](https://user-images.githubusercontent.com/29878131/97116418-95587180-16c2-11eb-9bdf-3f1c88cf3723.png)

Distro: Archlinux
Dirver version: 455.28
nvtop version: 1.0.0
GPU: RTX 2060 Mobile

**Comment by Syllo** [comment]
I added a special case when both information are not provide by the driver in the commit aa48ce2fc3750c87e23acd13d290ea8deed79a0c.
It should show up now with the current master branch version.

**Comment by Cherenkov11** [comment]
Yep, now is working correctly. Thanks

![Captura de pantalla de 2020-11-11 13-32-45](https://user-images.githubusercontent.com/29878131/98856218-dd95c480-2422-11eb-9554-633f08514d42.png)
