### ISSUE TITLE
putty session on 2k screen hide command lines

### ISSUE THREAD

**Issue by Saentist** [Syllo/nvtop#80]
Screen resolution 2560x1440
on full screen window command lines are hidden /scrolling not help/
![big](https://user-images.githubusercontent.com/16975883/98679789-30ab4100-2369-11eb-899c-e35dae088c0e.png)

if reduce horizontal size they appear
![small](https://user-images.githubusercontent.com/16975883/98679807-36088b80-2369-11eb-988b-f79a71a3fa3d.png)

over 2120 horizontal pixels are hidden

Any suggestions?

**Comment by Syllo** [comment]
Hello,

Did you set the setting in putty as instructed in the README?
``Terminal-type string`` to ``putty`` in the menu Connection > Data > Terminal Details.

**Comment by Saentist** [comment]
Strange is that there is no problem if Ubuntu 16.04 or CentOS 7 used 
Problem is on 18.04

Never set string before

**Comment by Syllo** [comment]
With the same version of nvtop on both systems?

So the problem fixes itself when you reduce the number of columns (and columns only)?
Could you please provide what the last number of column after which the display breaks?

This might be a bug that appeared when switching to a new version of libncurses or introduced in ncurses, but the former is more probable.

**Comment by Saentist** [comment]
At monday will report or will count on image ;)

**Comment by Saentist** [comment]
So there is problem after **305** horizontal columns or more exist 
aka **304** columns is maximum

**Comment by Syllo** [comment]
I was not able to reproduce at the time and nothing in the code could indicate anything breaking after 305 columns.
I suspect that this could have been a putty or ncurses issue, considering that this appears on different systems with the same nvtop version.
Feel free to re-open if the issue persists.
