### ISSUE TITLE
new release tag request: 1.0.0 is far behind the master branch.

### ISSUE THREAD

**Issue by vowstar** [Syllo/nvtop#83]
The latest release tag is https://github.com/Syllo/nvtop/releases/tag/1.0.0, and it is far behind the master branch.
This may brings problems to many Linux distributions that want to use the latest version of the package. Could an updated release tag be issued if it is convenient? Thank you!

**Comment by Syllo** [comment]
Thanks, you are right and I should have created a new release some time earlier.

I published a new minor release right now.
The distributions should catch up any time now :smile:
