### ISSUE TITLE
GPU Memory column and sort do not match

### ISSUE THREAD

**Issue by heeen** [Syllo/nvtop#84]
![image](https://user-images.githubusercontent.com/1699754/101761708-c5c26680-3adc-11eb-81b7-517ee07ecc61.png)

sorting by GPU memory does not seem to bring the biggest values to the top  - or the gpu memory column mixes host/gpu shared memory

**Comment by Syllo** [comment]
Hi,

Thanks for the report.
Can you please check that the version present in the branch ``fix_sort`` of the repository fixed your issue?

**Comment by ChrFrFn** [comment]
Hi,

the GPU column is always 0 like above even if the overall GPU is > 95%. For testing I used this CUDA benchmark program: http://www.roylongbottom.org.uk/linux_cuda_mflops.htm This results in 100% CPU and GPU usage.

![nvtop_0_percent_gpu_err](https://user-images.githubusercontent.com/82173186/114069354-31f08380-989f-11eb-8e87-0fb2509678aa.png)

I use the current commit on master.

**Comment by ChrFrFn** [comment]
Little hint to branch per_process_utilization: Benchmark test looks like above but CPU also is 0% like GPU which is less correct than master.

**Comment by Syllo** [comment]
The GPU column was referring to device number (different when having more than one GPU on the system).
The latest master version supports per process utilization and this column has been renamed DEV.
