### ISSUE TITLE
Does not display running processes

### ISSUE THREAD

**Issue by Thulashitharan** [Syllo/nvtop#86]
Nvtop does not display running processes.
![image](https://user-images.githubusercontent.com/64632995/102963775-fdcf9d80-450f-11eb-992b-cd98447ad24f.png)
Distro-kubuntu 20.10
Driver version-460.27.04
Using x-org
Kernel version-5.8.0-26-generic

**Comment by Syllo** [comment]
Sorry but there seems to be a lack of support by the nvml library for your GPU, hence the missing information in nvtop.
It may be due to the old age of the GPU (2013).

**Comment by cracket** [comment]
I have the same issue, but GPU is slightly newer:  NVIDIA Corporation GK104M [GeForce GTX 880M]
Built from sources on Ubuntu 18.04, needed to download nvml by cmake.
Any suggestion what should I check?  Based on readme:

> Anything starting at GeForce 600, GeForce 800M and successor should work fine

**Comment by Thulashitharan** [comment]
> Sorry but there seems to be a lack of support by the nvml library for your GPU, hence the missing information in nvtop.
> It may be due to the old age of the GPU (2013).

Yes.This is not an issue of nvtop :)
![image](https://user-images.githubusercontent.com/64632995/103433705-1af52200-4c1c-11eb-9eba-303610f5dcb1.png)
