### ISSUE TITLE
feature request: change graph update rate

### ISSUE THREAD

**Issue by timstd** [Syllo/nvtop#88]
Hi, thanks for this useful tool! Here's a feature that I miss and would further improve this tool: the ability to change the graph update rate. I know you can change the delay between updates with the command line argument -d, however this doesn't affect the graph update rate (seems to be fixed, updates about every second). A more precise visualization of the graph can be quite useful, so I think this feature would be a great addition.

**Comment by timstd** [comment]
#72

**Comment by alexcomo95** [comment]
Running 1.1.0, the delay with option "-d" only affects the list under the graph, not the graph.
