### ISSUE TITLE
Man folder don't use the prefix path

### ISSUE THREAD

**Issue by Alexsaphir** [Syllo/nvtop#89]
When manually building and installing with a custom prefix path, the binary is copied to the correct path but the man folder use the default location.

If it's the intended way, alright but if it isn't, adding the prefix path before /share/ in the CMakeFiles.txt allow to use the custom path.

**Comment by Syllo** [comment]
The prefix shouldn't be fixed.
The way to do it is ``make DESTDIR=/install/path install`` for example.
Or during cmake configuration ``cmake .. -DCMAKE_INSTALL_PREFIX=/install/path``

**Comment by Syllo** [comment]
Close for inactivity.
Feel free to re-open if the problem persists.
