### ISSUE TITLE
make on ubuntu 18 issue

### ISSUE THREAD

**Issue by adamnitzan** [Syllo/nvtop#99]
Installed two weeks ago and it worked. 
Tried again today with a different machine. Got the following on make

CMakeFiles/nvtop.dir/extract_gpuinfo.c.o: In function `update_device_infos':
extract_gpuinfo.c:(.text+0x105d): undefined reference to `nvmlDeviceGetGraphicsRunningProcesses_v2'
extract_gpuinfo.c:(.text+0x1125): undefined reference to `nvmlDeviceGetComputeRunningProcesses_v2'
collect2: error: ld returned 1 exit status
src/CMakeFiles/nvtop.dir/build.make:253: recipe for target 'src/nvtop' failed
make[2]: *** [src/nvtop] Error 1
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/nvtop.dir/all' failed
make[1]: *** [src/CMakeFiles/nvtop.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Syllo** [comment]
You could install ``apt install libnvidia-ml-dev`` to get the good header (if you installed the driver from the ubuntu repository). 
Then remove everything in the ``build`` directory and restart the compilation at the ```cmake ..``` stage (without the -DRETRIEVE...).

**Comment by Syllo** [comment]
This problem should be fixed with the latest version in the master branch.

**Comment by adamnitzan** [comment]
Tnx! 
It now works

**Comment by Syllo** [comment]
You are welcome!
Take care.
